### ISSUE TITLE
duplicate key value violates unique constraint

### ISSUE THREAD

**Issue by spuckydaslama** [javers/javers#1015]
When commiting changes we sometimes! (not exactly repeatable) get this exception:
` org.javers.common.exception.JaversException: SQL_EXCEPTION: FEHLER: doppelter Schl?sselwert verletzt Unique-Constraint ?jv_commit_pk?
   Detail: Schl?ssel ?(commit_pk)=(125)? existiert bereits.
 while executing sql: INSERT INTO kernanwendung.jv_commit ( author, commit_date, commit_date_instant, commit_id, commit_pk ) VALUES  ( ?,?,?,?,? )
 	at org.javers.repository.sql.session.PreparedStatementExecutor.wrapExceptionAndCall(PreparedStatementExecutor.java:120) ~[javers-persistence-sql-5.9.4.jar:na]
 	at org.javers.repository.sql.session.PreparedStatementExecutor.runVoidSql(PreparedStatementExecutor.java:110) ~[javers-persistence-sql-5.9.4.jar:na]
 	at org.javers.repository.sql.session.PreparedStatementExecutor.execute(PreparedStatementExecutor.java:39) ~[javers-persistence-sql-5.9.4.jar:na]
 	at org.javers.repository.sql.session.Session.execute(Session.java:105) ~[javers-persistence-sql-5.9.4.jar:na]
 	at org.javers.repository.sql.session.Session.executeInsertAndGetSequence(Session.java:52) ~[javers-persistence-sql-5.9.4.jar:na]
 	at org.javers.repository.sql.session.InsertBuilder.executeAndGetSequence(InsertBuilder.java:54) ~[javers-persistence-sql-5.9.4.jar:na]
 	at org.javers.repository.sql.repositories.CommitMetadataRepository.save(CommitMetadataRepository.java:35) ~[javers-persistence-sql-5.9.4.jar:na]
 	at org.javers.repository.sql.JaversSqlRepository.persist(JaversSqlRepository.java:86) ~[javers-persistence-sql-5.9.4.jar:na]
 	at org.javers.repository.api.JaversExtendedRepository.persist(JaversExtendedRepository.java:154) ~[javers-core-5.9.4.jar:na]
 	at org.javers.core.JaversCore.persist(JaversCore.java:105) ~[javers-core-5.9.4.jar:na]
 	at org.javers.core.JaversCore.commit(JaversCore.java:86) ~[javers-core-5.9.4.jar:na]
	...`

**Javers' Version**
'org.javers:javers-core:5.9.4'
'org.javers:javers-persistence-sql:5.9.4'

**Additional context**
Maybe the following context helps.
The error is reproducable on our ci, where we run an e2e(cypress) test that is talking with a backend(dockerised) that is committing changes via javers.

Running the tests locally (not dockerised), the tests won't fail.

**Comment by spuckydaslama** [comment]
i am closing this issue for now cause i saw my classpath contains 2 different versions of javers and one is 5.7.7 where a similar bug has already been found and fixed in 5.8

**Comment by spuckydaslama** [comment]
Sadly the versions were not the cause. Actually the module, where the exception pops up, was already on version 5.9.4.

**Comment by bartoszwalacik** [comment]
@spuckydaslama please follow the [guidelines-for-bug-reporting](https://github.com/javers/javers/blob/master/CONTRIBUTING.md#guidelines-for-bug-reporting) -- provide a failing test case, otherowise this issue will be closed
