### ISSUE TITLE
Exception during comparing String value - java.lang.ClassCastException: org.javers.core.metamodel.property.MissingProperty incompatible with java.lang.String

### ISSUE THREAD

**Issue by ArkadiuszBlejwas** [javers/javers#1076]
Using Javers I created custom comparator for String value so that null and empty String treat as same value. During manual tests in private project (I cant show you code of this project) I came accross such an exception:

> java.lang.ClassCastException: org.javers.core.metamodel.property.MissingProperty incompatible with java.lang.String
> at .StringComparator.compare(StringComparator.java:21)
> at org.javers.core.diff.custom.CustomToNativeAppenderAdapter.calculateChanges(CustomToNativeAppenderAdapter.java:33)
> at org.javers.core.diff.DiffFactory.appendChanges(DiffFactory.java:153)
> at org.javers.core.diff.DiffFactory.appendPropertyChanges(DiffFactory.java:143)
> at org.javers.core.diff.DiffFactory.createAndAppendChanges(DiffFactory.java:125)
> at org.javers.core.diff.DiffFactory.create(DiffFactory.java:69)
> at org.javers.core.diff.DiffFactory.compare(DiffFactory.java:54)
> at org.javers.core.JaversCore.compare(JaversCore.java:175)
> ...

This is what StringComparator look like:

```
class StringComparator implements CustomPropertyComparator<String, SetChange> {

    StringComparator() {
    }
    
    @Override
    public Optional<SetChange> compare(String originString, String modifizierteString,
            PropertyChangeMetadata propertyChangeMetadata, Property property) {
        if (equals(originString, modifizierteString)) {
            return Optional.empty();
        } else {
            final Set<Character> leftSet = getSetCharacterFromString(originString);
            final Set<Character> rightSet = getSetCharacterFromString(modifizierteString);

            return getSetChangeFromDiffrentSets(leftSet, rightSet, propertyChangeMetadata);
        }
    }

    @Override
    public boolean equals(String s1, String s2) {
        return StringUtils.equals(StringUtils.defaultString(s1), StringUtils.defaultString(s2));
    }

    @Override
    public String toString(String s) {
        return s;
    }
    
    private Set<Character> getSetCharacterFromString(String s) {
        return !isNull(s) ? s.chars().mapToObj(c -> (char) c).collect(Collectors.toSet()) : null;
    }
}
```
Can anyone tell me whether this is a javers bug or my code bug? I think I am not able to debug it, because immediately throws exception.

**Javers' Version**
5.14

**Comment by bartoszwalacik** [comment]
the exception is explicit, the problem is in this line : `vwg.service42.s42webclient.presentation.model.massnahme.aenderungserfassung.StringComparator.compare(StringComparator.java:21`
which line it is?

**Comment by ArkadiuszBlejwas** [comment]
class StringComparator implements CustomPropertyComparator<String, SetChange> {

**Comment by bartoszwalacik** [comment]
looks like a bug in javers, it probably happens when you compare two objects with different type definition but the same type name

**Comment by bartoszwalacik** [comment]
@ArkadiuszBlejwas consider contributing a PR with the fix, there are lot of issues here and one only maintainer

**Comment by ArkadiuszBlejwas** [comment]
@bartoszwalacik I want to contribute but you should take into account that I have little professional experience in programming. I can try find bug but I promise nothing.

**Comment by ArkadiuszBlejwas** [comment]
@bartoszwalacik what is PR? pull request?

**Comment by bartoszwalacik** [comment]
Arkadiusz, if you want to became a professional developer, you have to learn how to use google :)
https://www.google.com/search?q=what+is+pr+github

**Comment by ArkadiuszBlejwas** [comment]
@bartoszwalacik I will try debug this problem in next weekend, ok? I have also an idea for new features in javers. If you will like them, I will be happy to implement them.

**Comment by ArkadiuszBlejwas** [comment]
@bartoszwalacik I also have a request for you. Can you remove the comment asking for the 21 lines of code? There is information about the name of the project there, and I think I should not share such things. This is a commercial project. I've just noticed it now. My post has already been edited.

**Comment by mccartney** [comment]
Is `getSetChangeFromDiffrentSets` supposed to be some already existing library method? Or is it lacking from the example?

**Comment by bartoszwalacik** [comment]
`getSetChangeFromDiffrentSets` isn't a javers method

**Comment by bartoszwalacik** [comment]
we need a working test case , see https://github.com/javers/javers/blob/master/CONTRIBUTING.md#guidelines-for-bug-reporting

**Comment by AneenaThasneem** [comment]
Hi @bartoszwalacik and team,

After deeper analysis, this appears to be a design issue where:
- The `CustomPropertyComparator<T>` contract implies type safety
- But JaVers passes `MissingProperty` (breaking the contract)

@bartoszwalacik Would you accept a PR that either:

Auto-converts MissingProperty to null before comparison, or

At least documents this requirement prominently?

**Comment by bartoszwalacik** [comment]
fix released in 7.11.8
