### ISSUE TITLE
ERROR: relation "jv_global_id" already exists

### ISSUE THREAD

**Issue by alabotski** [javers/javers#1174]
Javers 6.5.3

I added annotation - JaversSpringDataAuditable
```
@JaversSpringDataAuditable
public interface LimitRepository extends JpaRepository<LimitEntity, UUID>, QuerydslPredicateExecutor<LimitEntity> {

}
```

Application.yml
```
javers:
  dialect: POSTGRES
```

So when I started application first time all work fine.
4 tables have been created

- jv_commit
- jv_commit_property
- jv_global_id
- jv_snapshot

But when I restart application I have such error

```
Caused by: org.postgresql.util.PSQLException: ERROR: relation "jv_global_id" already exists
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2674)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2364)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:354)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:484)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:404)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:325)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:311)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:287)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:282)
	at com.zaxxer.hikari.pool.ProxyStatement.execute(ProxyStatement.java:94)
	at com.zaxxer.hikari.pool.HikariProxyStatement.execute(HikariProxyStatement.java)
	at org.polyjdbc.core.schema.SchemaManagerImpl.ddl(SchemaManagerImpl.java:88)
	... 55 common frames omitted
```

**Comment by alabotski** [comment]
Seems my problem related to schema (dev)

```
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test?currentSchema=dev
    username: postgres
    password: postgres
```

if I work with public (jdbc:postgresql://localhost:5432/test) all works fine

**Comment by bartoszwalacik** [comment]
@alabotski if you want to report a bug please provide a failing test case see https://github.com/javers/javers/blob/master/CONTRIBUTING.md#guidelines-for-bug-reporting

**Comment by iwek7** [comment]
I had simillar issue it was solved by configuring javers schema in `application.yml`

```
javers:
  sqlSchema: nameOfYourSchema
```
