### ISSUE TITLE
MANAGED_CLASS_MAPPING_ERROR with Protobuf LazyStringArrayList

### ISSUE THREAD

**Issue by fairdincum** [javers/javers#1225]
**Clear description of my expectations versus reality**
I expected to be able to get a diff of two protobuf objects but it throws an exception.
```
  JaversException MANAGED_CLASS_MAPPING_ERROR: given javaClass 'class com.google.protobuf.LazyStringArrayList' is mapped to ListType, expected ManagedType
      at org.javers.core.protobuf.ProtobufDiffTest.should calculate diff for Protobufs(ProtobufDiffTest.groovy:16)


ProtobufDiffTest > should calculate diff for Protobufs FAILED
    JaversException MANAGED_CLASS_MAPPING_ERROR: given javaClass 'class com.google.protobuf.LazyStringArrayList' is mapped to ListType, expected ManagedType
        at org.javers.core.metamodel.type.TypeMapper.getJaversManagedType(TypeMapper.java:171)
        at org.javers.core.metamodel.type.TypeMapper.getJaversManagedType(TypeMapper.java:154)
        at org.javers.core.metamodel.object.GlobalIdFactory.createId(GlobalIdFactory.java:45)
        at org.javers.core.graph.LiveCdoFactory.create(LiveCdoFactory.java:37)
        at org.javers.core.graph.EdgeBuilder.buildSingleEdge(EdgeBuilder.java:33)
        at org.javers.core.graph.ObjectGraphBuilder.buildSingleEdges(ObjectGraphBuilder.java:107)
        at org.javers.core.graph.ObjectGraphBuilder.buildEdges(ObjectGraphBuilder.java:97)
        at org.javers.core.graph.ObjectGraphBuilder.buildGraphFromCdo(ObjectGraphBuilder.java:65)
        at org.javers.core.graph.ObjectGraphBuilder.buildGraph(ObjectGraphBuilder.java:54)
        at org.javers.core.graph.LiveGraphFactory.createLiveGraph(LiveGraphFactory.java:38)
        at org.javers.core.diff.DiffFactory.buildGraph(DiffFactory.java:102)
        at org.javers.core.diff.DiffFactory.compare(DiffFactory.java:55)
        at org.javers.core.JaversCore.compare(JaversCore.java:176)
        at org.javers.core.protobuf.ProtobufDiffTest.should calculate diff for Protobufs(ProtobufDiffTest.groovy:16)
```

**Steps To Reproduce**
I have a **runnable test case ** which isolates the bug and allows Javers Core Team to easily reproduce it. I have pushed this test case to my fork of this repository:

https://github.com/fairdincum/javers/blob/master/javers-core/src/test/groovy/org/javers/core/protobuf/ProtobufDiffTest.groovy

**Javers' Version**
6.7.1

**Additional context**
The model is a generated protobuf class from the definition that is in the comment at the [top of the class](https://github.com/fairdincum/javers/blob/master/javers-core/src/test/java/org/javers/core/examples/model/ResourcesOuterClass.java#L5).

**Comment by bartoszwalacik** [comment]
thanks for reporting, I don't know why this exception is thrown -- it needs research. Would you like to fix it?

**Comment by fairdincum** [comment]
I could probably spend some time investigating it if you give me some hints. At this point, I know next to nothing about Javers design.

**Comment by bartoszwalacik** [comment]
one should start from investigating the object graphs that are passed to compare()

what classes are in each node, what are the relationships, check the source code of each class

**Comment by bartoszwalacik** [comment]
Hi @fairdincum could you please improve your test case a bit?
- provide the original class (the domain object class)
- generate the protobuf class in the test setup (as we don't want to commit it the the repo)

**Comment by fairdincum** [comment]
We don't need this change any more, I'm going to close the PR.
