### ISSUE TITLE
CLASS_NOT_MANAGED error in 'java.util.ArrayList'

### ISSUE THREAD

**Issue by eladh** [javers/javers#130]
Hi.

we getting errors about CLASS_NOT_MANAGED  exceptions .

is there default support for collections ?

we are using Java Map/Set/Array Impl's and also Google MultiMap 

do we need to provide some kind of custom serializer ?

10x 

exception is JaversException: CLASS_NOT_MANAGED JaVers runtime error - given javaClass 'java.util.ArrayList' is mapped to ListType, ManagedType expected
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:597)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1094)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:989)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:504)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:475)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:304)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:228)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:300)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:195)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:703)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:760)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:482)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:109)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:691)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:320)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:952)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:941)
	at com.idi.pearl.crm.war.CrmServer.main(CrmServer.java:23)
Caused by: org.springframework.beans.factory.BeanDefinitionStoreException: Factory method [public org.javers.core.Javers com.idi.pearl.crm.config.AuditConfiguration.javers()] threw exception; nested exception is JaversException: CLASS_NOT_MANAGED JaVers runtime error - given javaClass 'java.util.ArrayList' is mapped to ListType, ManagedType expected
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:188)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:586)
	... 17 more
Caused by: JaversException: CLASS_NOT_MANAGED JaVers runtime error - given javaClass 'java.util.ArrayList' is mapped to ListType, ManagedType expected
	at org.javers.core.metamodel.type.TypeMapper.getJaversManagedType(TypeMapper.java:111)
	at org.javers.core.metamodel.object.GlobalIdFactory.getManagedClassOf(GlobalIdFactory.java:90)
	at org.javers.core.metamodel.object.GlobalIdFactory.createId(GlobalIdFactory.java:34)
	at org.javers.core.graph.LiveCdoFactory.create(LiveCdoFactory.java:18)
	at org.javers.core.graph.EdgeBuilder.asCdo(EdgeBuilder.java:39)
	at org.javers.core.graph.EdgeBuilder.buildSingleEdge(EdgeBuilder.java:32)
	at org.javers.core.graph.ObjectGraphBuilder.buildSingleEdges(ObjectGraphBuilder.java:77)

**Comment by eladh** [comment]
hi ,

after registering with 
builder.registerValueObject  i got the proper result 

10x :+1:

**Comment by bartoszwalacik** [comment]
no problem :)

**Comment by ucjonathan** [comment]
I'm having this exact issue right now.  My post on [Stackoverflow is here](http://stackoverflow.com/questions/35242048/managed-class-mapping-error-given-javaclass-class-java-util-arraylist-is-mappe).  @eladh can you show me what the code looks like to register that value object to avoid the error?  The weirdest part is it doesn't happen every time I run my sample program, but only about 30-40% of the time.

**Comment by bartoszwalacik** [comment]
@ucjonathan your issue and this could be totally unrelated, we will try to help you but we need to reproduce your exception on our laptops. See my response on stackoverflow and plese continue the thread on stackoverflow
