### ISSUE TITLE
Unable to work with Google Collections - SetMultimap

### ISSUE THREAD

**Issue by eladh** [javers/javers#132]
Hi.

as a first setup i need to investigate changes on complex Aggregator MD object graph.

one of the data structures is Google Collections - SetMultimap  and when i start the Javers  JaversBuilder i got the following error : 

given javaClass 'com.google.common.collect.AbstractMultimap$WrappedSet' is mapped to SetType, ManagedType expected

after registering the inner  we getting error in BeanBasedPropertyScanner->ReflectionUtils->isPersistentGetter->isGetter

10x

**Comment by eladh** [comment]
error :

Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: 3
	at java.lang.String.substring(String.java:1907)
	at org.javers.common.reflection.ReflectionUtil.isGetter(ReflectionUtil.java:100)
	at org.javers.common.reflection.ReflectionUtil.isPersistentGetter(ReflectionUtil.java:83)
	at org.javers.common.reflection.ReflectionUtil.findAllPersistentGetters(ReflectionUtil.java:55)
	at org.javers.core.metamodel.property.BeanBasedPropertyScanner.scan(BeanBasedPropertyScanner.java:23)
	at org.javers.core.metamodel.clazz.ManagedClassFactory.create(ManagedClassFactory.java:90)
	at org.javers.core.metamodel.clazz.ManagedClassFactory.create(ManagedClassFactory.java:64)
	at org.javers.core.metamodel.type.TypeFactory.createFromDefinition(TypeFactory.java:29)
	at org.javers.core.metamodel.type.TypeMapper.registerClientsClass(TypeMapper.java:163)
	at org.javers.core.JaversBuilder.mapRegisteredClasses(JaversBuilder.java:328)
	at org.javers.core.JaversBuilder.bootManagedClasses(JaversBuilder.java:346)
	at org.javers.core.JaversBuilder.assembleJaversInstance(JaversBuilder.java:99)
	at org.javers.core.JaversBuilder.build(JaversBuilder.java:88)

**Comment by eladh** [comment]
hi

the issue here :

what if the method name is just "is" , then you will get the following exception 

   public static boolean isGetter(Method m) {
        return (m.getName().substring(0,3).equals("get")  ||
                m.getName().substring(0,2).equals("is") ) &&
                m.getParameterTypes().length == 0;
    }

**Comment by bartoszwalacik** [comment]
JaVers do not support Guava collection types out-of-the-box.
Take look at http://javers.org/documentation/diff-configuration/#custom-comparators
this is know issue

We need a set of custom-comparators for Guava collection types, you can write it and then we encourage you to contribute this to JaVers

**Comment by bgalek** [comment]
looking forward for users contribution :)

**Comment by bartoszwalacik** [comment]
released in 2.9.0
