### ISSUE TITLE
Javers - MongoDb - JaversException: CLASS_NOT_FOUND

### ISSUE THREAD

**Issue by dggit** [javers/javers#135]
Hello,
First thanks for this wonderful tool !

I am trying to link MongoDb with Javers on a model called Property.
(I am using play framework Java)

Here is my class : 
public class Property extends IdObjectId  {

    public Property(){
        this.stateFields = new StateFields();
        this.searchFields = new PropertySearchFields();
        this.matchingFields = new MatchingFields();
    }

    public Integer propertyId;
    public Integer criteriaId;
    public StateFields stateFields;
    public PropertySearchFields searchFields;
    @DiffIgnore
    public MatchingFields matchingFields;

Then i configure Javers : 

        Javers javers = JaversBuilder.javers()
                .registerValueTypeAdapter(new ObjectIdTypeAdapter())
                .registerJaversRepository(mongoRepo)
                .build();
        Property p1 = Property.findOneBy("stateFields.reference", ref1);
        javers.commit("property", p1);

        p1.propertyId = 200000;
        javers.commit("property", p1);

And I get this exception : 
```
play.api.Application$$anon$1: Execution exception[[JaversException: CLASS_NOT_FOUND JaVers runtime error - class not found - 'utils.property.PropertySearchFields']]
	at play.api.Application$class.handleError(Application.scala:296) ~[play_2.10-2.3.6.jar:2.3.6]
	at play.api.DefaultApplication.handleError(Application.scala:402) [play_2.10-2.3.6.jar:2.3.6]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [play_2.10-2.3.6.jar:2.3.6]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [play_2.10-2.3.6.jar:2.3.6]
	at scala.Option.map(Option.scala:145) [scala-library.jar:na]
Caused by: org.javers.common.exception.JaversException: CLASS_NOT_FOUND JaVers runtime error - class not found - 'utils.property.PropertySearchFields'
	at org.javers.core.json.typeadapter.commit.GlobalIdTypeAdapter.parseClass(GlobalIdTypeAdapter.java:127) ~[javers-core-1.1.1.jar:na]
	at org.javers.core.json.typeadapter.commit.GlobalIdTypeAdapter.parseValueObjectId(GlobalIdTypeAdapter.java:58) ~[javers-core-1.1.1.jar:na]
	at org.javers.core.json.typeadapter.commit.GlobalIdTypeAdapter.fromJson(GlobalIdTypeAdapter.java:46) ~[javers-core-1.1.1.jar:na]
	at org.javers.core.json.typeadapter.commit.GlobalIdTypeAdapter.fromJson(GlobalIdTypeAdapter.java:20) ~[javers-core-1.1.1.jar:na]
	at org.javers.core.json.JsonConverterBuilder$2.deserialize(JsonConverterBuilder.java:132) ~[javers-core-1.1.1.jar:na]
```

It saves elements in mongodb collection jv_snapshots : 

```
{
    "_id" : ObjectId("551815c930040e229ecca60e"),
    "commitMetadata" : {
        "author" : "property",
        "commitDate" : "2015-03-29T17:10:01",
        "id" : "30.0"
    },
    "globalId" : {
        "valueObject" : "utils.property.PropertySearchFields",
        "ownerId" : {
            "entity" : "models.Property",
            "cdoId" : "5517284a300480cf1549e4fe"
        },
        "fragment" : "searchFields"
    },
    "state" : {
        "livingSurface" : 250,
        "bedroomsNb" : 0,
        "propertyParentType" : 3,
        "cityId" : 31555,
        "districtId" : 102288,
        "price" : 62000000,
        "roomsNb" : 0,
        "siteSurface" : 160
    },
    "type" : "INITIAL",
    "globalId_key" : "models.Property/5517284a300480cf1549e4fe#searchFields"
}

/* 1 */
{
    "_id" : ObjectId("551815c930040e229ecca60f"),
    "commitMetadata" : {
        "author" : "property",
        "commitDate" : "2015-03-29T17:10:01",
        "id" : "30.0"
    },
    "globalId" : {
        "entity" : "models.Property",
        "cdoId" : "5517284a300480cf1549e4fe"
    },
    "state" : {
        "id" : "5517284a300480cf1549e4fe",
        "searchFields" : {
            "valueObject" : "utils.property.PropertySearchFields",
            "ownerId" : {
                "entity" : "models.Property",
                "cdoId" : "5517284a300480cf1549e4fe"
            },
            "fragment" : "searchFields"
        },
        "stateFields" : {
            "valueObject" : "utils.StateFields",
            "ownerId" : {
                "entity" : "models.Property",
                "cdoId" : "5517284a300480cf1549e4fe"
            },
            "fragment" : "stateFields"
        }
    },
    "type" : "INITIAL",
    "globalId_key" : "models.Property/5517284a300480cf1549e4fe"
}

/* 2 */
{
    "_id" : ObjectId("551815c930040e229ecca610"),
    "commitMetadata" : {
        "author" : "property",
        "commitDate" : "2015-03-29T17:10:01",
        "id" : "30.0"
    },
    "globalId" : {
        "valueObject" : "utils.StateFields",
        "ownerId" : {
            "entity" : "models.Property",
            "cdoId" : "5517284a300480cf1549e4fe"
        },
        "fragment" : "stateFields"
    },
    "state" : {
        "title" : " immeuble 3108316",
        "enabled" : true,
        "userObjectId" : "551459799f0658d7e46179c1",
        "reference" : "3108316",
        "masterObjectId" : "5514597a9f0658d7e46185ef",
        "clientInfo" : "Agence My toulouse",
        "userInfo" : "caroline ayroles"
    },
    "type" : "INITIAL",
    "globalId_key" : "models.Property/5517284a300480cf1549e4fe#stateFields"
}
```

but the second .commit() brings the exception.

If i remove registerJaversRepository it works fine.

If i put @DiffIgnore on all fields just to test it even throw me this one : 

```
Caused by: org.javers.common.exception.JaversException: CLASS_NOT_FOUND JaVers runtime error - class not found - 'models.Property'
	at org.javers.core.json.typeadapter.commit.GlobalIdTypeAdapter.parseClass(GlobalIdTypeAdapter.java:127) ~[javers-core-1.1.1.jar:na]
	at org.javers.core.json.typeadapter.commit.GlobalIdTypeAdapter.parseEntity(GlobalIdTypeAdapter.java:117) ~[javers-core-1.1.1.jar:na]
	at org.javers.core.json.typeadapter.commit.GlobalIdTypeAdapter.parseInstanceId(GlobalIdTypeAdapter.java:66) ~[javers-core-1.1.1.jar:na]
	at org.javers.core.json.typeadapter.commit.GlobalIdTypeAdapter.fromJson(GlobalIdTypeAdapter.java:44) ~[javers-core-1.1.1.jar:na]
	at org.javers.core.json.typeadapter.commit.GlobalIdTypeAdapter.fromJson(GlobalIdTypeAdapter.java:20) ~[javers-core-1.1.1.jar:na]
```

the @Id annotation is in the class IdObjectId : 
```
public  class IdObjectId extends MongoModel{

    @Id
    private String id;

    @ObjectId
    @JsonProperty("_id")
    public String getId() {
        return id;
    }
    @ObjectId
    @JsonProperty("_id")
    public void setId(String id) {
        this.id = id;
    }
    @JsonIgnore
    public org.bson.types.ObjectId getOId() { return new org.bson.types.ObjectId(id);}


}
```

Tried everything that is the documentation, didn't help.
Thanks.
Best Regards.

**Comment by bartoszwalacik** [comment]
Hello friend, this CLASS_NOT_FOUND looks really strange.
I will help you but I need to reproduce this exception. Please distill this issue as a small project with a failing test and push it to
the github.

**Comment by dggit** [comment]
Ok i try to create new project with the issue as soon as i have a moment.
Thanks for super fast answer.



Cordialement,
*Dara Ghazanfari*
*06 59 11 01 35*

**Comment by bgalek** [comment]
hope it's fixed already :)

**Comment by shoon** [comment]
The Playframework uses some magic to load classes and Class.forName will fail sometimes (DEV mode.) The preferred method is to use 
```java
Play.classloader.loadApplicationClass(qualifiedName);
```
I don't see an easy way to create a custom JsonConverter to fix this externally

**Comment by bartoszwalacik** [comment]
any suggestions?

**Comment by shoon** [comment]
What i thought I could do was create a custom JsonConverter... and set that in my repository (MongoRepository)... it would handle the parseClass the way Play requires

```java
    public static Class parseClass(String qualifiedName) {
        return Play.classloader.loadApplicationClass(qualifiedName);
    }
```
But it doesn't seem possible to extend the existing or pass in a custom JsonConverter to MongoRepository.setJsonConverter. Granted, I haven't had much time to root through the code and I'm stuck using 1.2.6 since I have a dependency on the older 2.x mongo client.

Perhaps make the JsonConverter an interface?

**Comment by shoon** [comment]
Actually maybe the right thing to do is have a custom repository?

**Comment by bartoszwalacik** [comment]
Tkink you need custom Class Loader ...

**Comment by shoon** [comment]
Well I tried a few things and I think it's cleanest to rip out the classes to be versioned from the Play project and into an external jar.... the class loading works just fine without the Play autocompiler/classloader magic.

How would you approach that custom class loader?

Also, here's the magic Play1 uses:

https://github.com/playframework/play1/blob/1.3.x/framework/src/play/classloading/ApplicationClassloader.java#L95-182

**Comment by bartoszwalacik** [comment]
Well, it could be just a plugin function wich you coud register in Javers. Like 
`Class load (String name)`. If you want to have it , think about contribution, we are open for pull requests.
