### ISSUE TITLE
Connection Leaks During Schema Management with JaVers

### ISSUE THREAD

**Issue by ej-feras** [javers/javers#1413]
We encountered connection leaks when using JaVers' automatic schema management in a Spring Boot project with PostgreSQL and jOOQ (without JPA). During schema validation or modification, JaVers opens database connections but does not properly return them to the connection pool. This results in connection exhaustion over time, with HikariCP reporting leaks (e.g., `Apparent connection leak detected`).

Expected Behavior:
JaVers should handle database connections efficiently during schema management. After schema-related operations (e.g., table creation, column adjustment), connections should be properly closed or returned to the connection pool to prevent resource exhaustion.

Actual Behavior:
When `withSchemaManagementEnabled(true)` is enabled, JaVers opens connections for schema management but does not return them, leading to connection leaks and pool exhaustion. Over time, this depletes the connection pool, causing performance degradation and database connection failures.

Connection Leak Message:
```

2024-09-12T14:28:42.703+02:00  WARN 35063 --- [l-1 housekeeper] com.zaxxer.hikari.pool.ProxyLeakTask     : Connection leak detection triggered for org.postgresql.jdbc.PgConnection@322925b5 on thread restartedMain, stack trace follows

java.lang.Exception: Apparent connection leak detected
    at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:128) ~[HikariCP-5.0.1.jar:na]
    at org.javers.repository.sql.schema.JaversSchemaManager.columnExists(JaversSchemaManager.java:200) ~[javers-persistence-sql-7.6.1.jar:na]
    at org.javers.repository.sql.schema.JaversSchemaManager.addCommitDateInstantColumnIfNeeded(JaversSchemaManager.java:71) ~[javers-persistence-sql-7.6.1.jar:na]
    at org.javers.repository.sql.schema.JaversSchemaManager.ensureSchema(JaversSchemaManager.java:62) ~[javers-persistence-sql-7.6.1.jar:na]
    at org.javers.repository.sql.JaversSqlRepository.ensureSchema(JaversSqlRepository.java:186) ~[javers-persistence-sql-7.6.1.jar:na]
    at org.javers.core.JaversBuilder.assembleJaversInstanceAndEnsureSchema(JaversBuilder.java:142) ~[javers-core-7.6.1.jar:na]
    at org.javers.core.JaversBuilder.build(JaversBuilder.java:133) ~[javers-core-7.6.1.jar:na]

```
Steps to Reproduce:
1. Use JaVers with Spring Boot and jOOQ (without JPA) in a PostgreSQL environment.
2. Enable automatic schema management using `withSchemaManagementEnabled(true)`.
3. Configure the application to use HikariCP for connection pooling.
4. Run the application and observe connection leaks as JaVers manages the schema.

Workaround:
We disabled schema management (`withSchemaManagementEnabled(false)`) and manually created the necessary JaVers tables. This resolves the connection leak issue but requires manual schema maintenance.

Environment:
- JaVers version: 7.6.1
- Java version: 17
- Spring Boot version: 2.7.18
- PostgreSQL JDBC Driver: 42.7.3
- HikariCP version: 5.0.1

```
Maven Dependencies:
<dependency>
    <groupId>org.javers</groupId>
    <artifactId>javers-core</artifactId>
    <version>7.6.1</version>
</dependency>

<dependency>
    <groupId>org.javers</groupId>
    <artifactId>javers-persistence-sql</artifactId>
    <version>7.6.1</version>
</dependency>
```

Configuration:

```
@Configuration
public class JaversConfig {

    private final DataSource dataSource;

    public JaversConfig(DataSource dataSource) {
        this.dataSource = dataSource;
    }

    @Bean
    public DataSourceTransactionManager transactionManager(DataSource dataSource) {
        return new DataSourceTransactionManager(dataSource);
    }

    @Bean
    public Javers javers() {
        JaversBuilder javersBuilder = JaversBuilder.javers()
                .registerJaversRepository(
                        SqlRepositoryBuilder
                                .sqlRepository()
                                .withSchema("public")
                                .withDialect(javersSqlDialectName())
                                .withSchemaManagementEnabled(false) // Manual schema management due to connection leaks
                                .withConnectionProvider(() -> DataSourceUtils.getConnection(dataSource))
                                .build());

        return javersBuilder.build();
    }

    @Bean
    public DialectName javersSqlDialectName() {
        return DialectName.POSTGRES;
    }
}
```

**Comment by bartoszwalacik** [comment]
PTAL https://github.com/javers/javers/issues/1366

**Comment by bartoszwalacik** [comment]
looks like a duplicate to https://github.com/javers/javers/issues/1366, feel free to reopen if you think it's a new case

**Comment by ej-feras** [comment]
@bartoszwalacik  still getting the same error aslo after upgrade to v7.6.2:

2024-09-20T13:00:37.892+02:00  WARN 44097 --- [iCP housekeeper] com.zaxxer.hikari.pool.ProxyLeakTask     : Connection leak detection triggered for org.postgresql.jdbc.PgConnection@5f5998fd on thread restartedMain, stack trace follows

java.lang.Exception: Apparent connection leak detected
        at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:127) ~[HikariCP-5.1.0.jar:na]
        at org.javers.repository.sql.SqlRepositoryBuilder.lambda$build$0(SqlRepositoryBuilder.java:127) ~[javers-persistence-sql-7.6.2.jar:na]
        at org.polyjdbc.core.transaction.ExternalTransactionManager.openTransaction(ExternalTransactionManager.java:18) ~[polyjdbc-0.7.6.jar:na]
        at org.polyjdbc.core.schema.SchemaManagerFactory.createInspector(SchemaManagerFactory.java:44) ~[polyjdbc-0.7.6.jar:na]
        at org.polyjdbc.core.DefaultPolyJDBC.schemaInspector(DefaultPolyJDBC.java:78) ~[polyjdbc-0.7.6.jar:na]
        at org.javers.repository.sql.schema.JaversSchemaManager.ensureSchema(JaversSchemaManager.java:43) ~[javers-persistence-sql-7.6.2.jar:na]
        at org.javers.repository.sql.JaversSqlRepository.ensureSchema(JaversSqlRepository.java:186) ~[javers-persistence-sql-7.6.2.jar:na]
        at org.javers.core.JaversBuilder.assembleJaversInstanceAndEnsureSchema(JaversBuilder.java:142) ~[javers-core-7.6.2.jar:na]
        at org.javers.core.JaversBuilder.build(JaversBuilder.java:133) ~[javers-core-7.6.2.jar:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:146) ~[spring-beans-6.1.11.jar:6.1.11]
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:644) ~[spring-beans-6.1.11.jar:6.1.11]
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:485) ~[spring-beans-6.1.11.jar:6.1.11]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1355) ~[spring-beans-6.1.11.jar:6.1.11]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1185) ~[spring-beans-6.1.11.jar:6.1.11]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:562) ~[spring-beans-6.1.11.jar:6.1.11]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:522) ~[spring-beans-6.1.11.jar:6.1.11]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:337) ~[spring-beans-6.1.11.jar:6.1.11]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-6.1.11.jar:6.1.11]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:335) ~[spring-beans-6.1.11.jar:6.1.11]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[spring-beans-6.1.11.jar:6.1.11]
        at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:254) ~[spring-beans-6.1.11.jar:6.1.11]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1443) ~[spring-beans-6.1.11.jar:6.1.11]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1353) ~[spring-beans-6.1.11.jar:6.1.11]
        at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:904) ~[spring-beans-6.1.11.jar:6.1.11]
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:782) ~[spring-beans-6.1.11.jar:6.1.11]
        at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:237) ~[spring-beans-6.1.11.jar:6.1.11]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1375) ~[spring-beans-6.1.11.jar:6.1.11]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1212) ~[spring-beans-6.1.11.jar:6.1.11]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:562) ~[spring-beans-6.1.11.jar:6.1.11]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:522) ~[spring-beans-6.1.11.jar:6.1.11]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:337) ~[spring-beans-6.1.11.jar:6.1.11]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-6.1.11.jar:6.1.11]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:335) ~[spring-beans-6.1.11.jar:6.1.11]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[spring-beans-6.1.11.jar:6.1.11]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:975) ~[spring-beans-6.1.11.jar:6.1.11]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:971) ~[spring-context-6.1.11.jar:6.1.11]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:625) ~[spring-context-6.1.11.jar:6.1.11]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146) ~[spring-boot-3.3.2.jar:3.3.2]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754) ~[spring-boot-3.3.2.jar:3.3.2]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:456) ~[spring-boot-3.3.2.jar:3.3.2]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:335) ~[spring-boot-3.3.2.jar:3.3.2]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1363) ~[spring-boot-3.3.2.jar:3.3.2]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]

**Comment by bartoszwalacik** [comment]
@ej-feras that would be a bit harder to fix as JaversSchemaManager still uses PolyJDBC, a library that is no longer maintained, see https://github.com/polyjdbc/polyjdbc. Could you please try to debug the issue?
