### ISSUE TITLE
Problem with Pair<L, R>: CLASS_EXTRACTION_ERROR JaVers bootstrap error - Don't know how to extract Class from type 'L'.

### ISSUE THREAD

**Issue by blaketsk** [javers/javers#150]
Hi there.
I'm using javers 1.0.3 and Apache Commons Pair (org.apache.commons.lang3.tuple.Pair).
```java
Pair<String, Integer> pair1 = new ImmutablePair<>("string1", 1);
Pair<String, Integer> pair2 = new ImmutablePair<>("string2", 2);
Javers javers = JaversBuilder.javers().build();
Diff diff = javers.compare(pair1, pair2);
```
And I got
```
JaversException: CLASS_EXTRACTION_ERROR JaVers bootstrap error - Don't know how to extract Class from type 'L'.
	at org.javers.common.reflection.ReflectionUtil.extractClass(ReflectionUtil.java:140)
	at org.javers.core.metamodel.type.TypeMapper.findNearestAncestor(TypeMapper.java:272)
	at org.javers.core.metamodel.type.TypeMapper.infer(TypeMapper.java:249)
	at org.javers.core.metamodel.type.TypeMapper.getJaversType(TypeMapper.java:81)
	at org.javers.core.metamodel.type.TypeMapper.getPropertyType(TypeMapper.java:101)
	at org.javers.core.metamodel.type.TypeMapper.isEntityReferenceOrValueObject(TypeMapper.java:105)
	at org.javers.core.graph.ObjectGraphBuilder$1.apply(ObjectGraphBuilder.java:104)
	at org.javers.core.graph.ObjectGraphBuilder$1.apply(ObjectGraphBuilder.java:102)
	at org.javers.core.metamodel.clazz.ManagedClass.getProperties(ManagedClass.java:40)
	at org.javers.core.graph.ObjectGraphBuilder.getSingleReferences(ObjectGraphBuilder.java:102)
	at org.javers.core.graph.ObjectGraphBuilder.buildSingleEdges(ObjectGraphBuilder.java:72)
	at org.javers.core.graph.ObjectGraphBuilder.buildEdges(ObjectGraphBuilder.java:67)
	at org.javers.core.graph.ObjectGraphBuilder.buildGraph(ObjectGraphBuilder.java:55)
	at org.javers.core.graph.LiveGraphFactory.createLiveGraph(LiveGraphFactory.java:28)
	at org.javers.core.diff.DiffFactory.buildGraph(DiffFactory.java:83)
	at org.javers.core.diff.DiffFactory.compare(DiffFactory.java:51)
	at org.javers.core.Javers.compare(Javers.java:130)
	at com.blabla.DiffUtilTest.testPair(DiffUtilTest.java:121)
```
I tried my own implementation of Pair:
```java
public class Pair<L, R> {

    private L left;
    private R right;

    public Pair(L left, R right) {
        this.left = left;
        this.right = right;
    }

    public L getLeft() {
        return left;
    }

    public R getRight() {
        return right;
    }
}
```
and still the same issue.

Am I doing something wrong?
Is it possible to use javers with generics?

**Comment by bartoszwalacik** [comment]
try new JaVers version, 1.2.0

**Comment by blaketsk** [comment]
Still the same with JaVers 1.2.0.
Example, if it helps: https://github.com/blaketsk/javers-test

**Comment by bartoszwalacik** [comment]
Apache Pair is ok, do not reimplement it. 
JaVers supports generics, but JaVers requires type mapping - concrete java types of your objects.
Without that it's impossible to compare them.

All unbounded type parameters like `L` should be statically resolvable to concrete java types.

In your case you can use sth like that:

```
public class StringToIntPair extends ImmutablePair<String, Integer> {
}

StringToIntPair  pair1 = new StringToIntPair  ("string1", 1);
StringToIntPair  pair2 = new StringToIntPair  ("string2", 2);
Javers javers = JaversBuilder.javers().build();
Diff diff = javers.compare(pair1, pair2);
```
