### ISSUE TITLE
java.lang.ClassCastException

### ISSUE THREAD

**Issue by TimSin** [javers/javers#155]
I get the following error when trying to commit a change to Javers using the javers.commit(user, currentVersion) call:

```
java.lang.ClassCastException: org.javers.core.metamodel.object.InstanceId cannot be cast to java.lang.Comparable
	at java.util.TreeMap.compare(TreeMap.java:1188)
	at java.util.TreeMap.put(TreeMap.java:531)
	at java.util.TreeSet.add(TreeSet.java:255)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:60)
	at com.google.gson.Gson.fromJson(Gson.java:803)
	at com.google.gson.Gson.fromJson(Gson.java:868)
	at org.javers.core.json.JsonConverter.fromJson(JsonConverter.java:86)
	at org.javers.core.json.JsonConverter$1.deserialize(JsonConverter.java:61)
	at org.javers.core.json.typeadapter.commit.CdoSnapshotStateDeserializer.decodePropertyValue(CdoSnapshotStateDeserializer.java:48)
	at org.javers.core.json.typeadapter.commit.CdoSnapshotStateDeserializer.deserialize(CdoSnapshotStateDeserializer.java:39)
	at org.javers.core.json.JsonConverter.snapshotStateFromJson(JsonConverter.java:108)
	at org.javers.repository.sql.finders.CdoSnapshotObjectMapper.createObject(CdoSnapshotObjectMapper.java:45)
	at org.javers.repository.sql.finders.CdoSnapshotObjectMapper.createObject(CdoSnapshotObjectMapper.java:24)
	at org.polyjdbc.core.query.TransactionalQueryRunner.queryCollection(TransactionalQueryRunner.java:90)
	at org.polyjdbc.core.query.TransactionalQueryRunner.queryList(TransactionalQueryRunner.java:76)
	at org.javers.repository.sql.finders.CdoSnapshotFinder.queryForCdoSnapshots(CdoSnapshotFinder.java:97)
	at org.javers.repository.sql.finders.CdoSnapshotFinder.getLatest(CdoSnapshotFinder.java:43)
	at org.javers.repository.sql.JaversSqlRepository.getLatest(JaversSqlRepository.java:40)
	at org.javers.repository.api.JaversExtendedRepository.getLatest(JaversExtendedRepository.java:100)
	at org.javers.core.snapshot.GraphShadowFactory.createLatestShadow(GraphShadowFactory.java:32)
	at org.javers.core.snapshot.GraphSnapshotFacade.createLatestShadow(GraphSnapshotFacade.java:22)
	at org.javers.core.commit.CommitFactory.create(CommitFactory.java:76)
	at org.javers.core.JaversCore.commit(JaversCore.java:56)
..... 
```
This works when just using the in memory version of javers:

```
 this.javers = JaversBuilder.javers().build()
```
But when trying to use an in memory H2 DB, the error occurs:
```
        final Connection dbConnection;
        try {
            Class.forName("org.h2.Driver");
            dbConnection = DriverManager.getConnection("jdbc:h2:mem:test");
        } catch (SQLException e) {
            throw new RuntimeException(e);
        } catch (ClassNotFoundException e) {
            throw new RuntimeException(e);
        }

        ConnectionProvider connectionProvider = new ConnectionProvider() {
            @Override
            public Connection getConnection() {
                // suitable only for testing!
                return dbConnection;
            }
        };

        JaversSqlRepository sqlRepository = SqlRepositoryBuilder.sqlRepository()
                .withConnectionProvider(connectionProvider).withDialect(DialectName.H2).build();
        this.javers = JaversBuilder.javers().registerJaversRepository(sqlRepository).build();
```
My domain model objects are all marked with @Id annotations on the correct fields and, as I mention above, changesets are being stored in the non-db backed version of Javers successfully. I've also tried backing with a mongo DB and hit the same issue.

Am I missing some configuration step here or is this an issue with Javers?

**Comment by TimSin** [comment]
Evidently it was a config issue. A browse through the Javers source revealed that any mapped collections that are managed by Hibernate require a @DiffIgnore annotation to ensure that serialisation works correctly.

**Comment by bartoszwalacik** [comment]
nice, we are working on `hibernate unproxying issue` - https://github.com/javers/javers/issues/91

after that Javers would be able to manage hibernate proxies
