### ISSUE TITLE
Javers + Spring data + Mongo does not work

### ISSUE THREAD

**Issue by swarooprath** [javers/javers#156]
I tried to create a simple example using Javers + Mongo + spring data + spring. It does not work and my application crashes before the context is initialized. I see that Javers uses deprecated api getDb on MongoClient below. The example on your website uses the constructor new Mongo() which is deprecated and fails as well. Am copying my code block, links to your website and stacktrace below.

Link to documentation: 
http://javers.org/documentation/spring-integration/

Code:
public class JaversMongoMain {
	public static void main(String args[]) {
		MongoRepository mongoRepo = new MongoRepository(new MongoClient().getDB("test"));
		System.out.print(3);
	}
}

Stacktrace : 
May 21, 2015 5:22:51 PM com.mongodb.diagnostics.logging.JULLogger log
INFO: Cluster created with settings {hosts=[127.0.0.1:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms', maxWaitQueueSize=500}
May 21, 2015 5:22:51 PM com.mongodb.diagnostics.logging.JULLogger log
INFO: Exception in monitor thread while connecting to server 127.0.0.1:27017
com.mongodb.MongoException: java.lang.IllegalAccessError: tried to access class com.mongodb.MongoNamespace from class com.mongodb.connection.CommandHelper
	at com.mongodb.connection.InternalStreamConnection.open(InternalStreamConnection.java:125)
	at com.mongodb.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:127)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalAccessError: tried to access class com.mongodb.MongoNamespace from class com.mongodb.connection.CommandHelper
	at com.mongodb.connection.CommandHelper.sendMessage(CommandHelper.java:86)
	at com.mongodb.connection.CommandHelper.executeCommand(CommandHelper.java:32)
	at com.mongodb.connection.InternalStreamConnectionInitializer.initializeConnectionDescription(InternalStreamConnectionInitializer.java:83)
	at com.mongodb.connection.InternalStreamConnectionInitializer.initialize(InternalStreamConnectionInitializer.java:43)
	at com.mongodb.connection.InternalStreamConnection.open(InternalStreamConnection.java:115)
	... 2 more

May 21, 2015 5:23:01 PM com.mongodb.diagnostics.logging.JULLogger log
INFO: Exception in monitor thread while connecting to server 127.0.0.1:27017
com.mongodb.MongoException: java.lang.IllegalAccessError: com/mongodb/MongoNamespace
	at com.mongodb.connection.InternalStreamConnection.open(InternalStreamConnection.java:125)
	at com.mongodb.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:127)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalAccessError: com/mongodb/MongoNamespace
	at com.mongodb.connection.CommandHelper.sendMessage(CommandHelper.java:86)
	at com.mongodb.connection.CommandHelper.executeCommand(CommandHelper.java:32)
	at com.mongodb.connection.InternalStreamConnectionInitializer.initializeConnectionDescription(InternalStreamConnectionInitializer.java:83)
	at com.mongodb.connection.InternalStreamConnectionInitializer.initialize(InternalStreamConnectionInitializer.java:43)
	at com.mongodb.connection.InternalStreamConnection.open(InternalStreamConnection.java:115)
	... 2 more

**Comment by swarooprath** [comment]
Here is a link to my repo. My attempt of saving one entity to Mongo using Spring + Spring data + Javers : https://github.com/swarooprath/mongo/tree/master/javers

**Comment by bartoszwalacik** [comment]
@swarooprath if you are using Mongo 3.0 - this is a known issue.
Javers works with Mongo 2.6, and simply does not work with Mongo 3.0. Mongo guys did braking changes in mongo-client API.

Upgrading javers to Mongo 3.0 is high in our backlog, we plan to make it happen in this month, stay tuned

**Comment by bartoszwalacik** [comment]
JaVers 1.2.5 is released. We updated MongoDB Java Driver to 3.0
http://javers.org/documentation/features/#release-notes
check it out

**Comment by swarooprath** [comment]
Thanks for fixing this, will check it. Yes, am on mongo3. 
Mongodb version is : db version v3.0.2
The version number of all the jars I used and along with the code are in my public github repo's build.gradle. Copying the link from above for easy reference: https://github.com/swarooprath/mongo/blob/master/javers/build.gradle
