### ISSUE TITLE
Registering more than one custom comparator throws exception

### ISSUE THREAD

**Issue by tomazic89** [javers/javers#172]
If you try to register more than one custom comparator the following exception is thrown:

*java.lang.ExceptionInInitializerError
Caused by: org.picocontainer.PicoCompositionException: Duplicate Keys not allowed. Duplicate for 'class org.javers.core.diff.custom.CustomToNativeAppenderAdapter'
	at org.picocontainer.DefaultPicoContainer.addAdapterInternal(DefaultPicoContainer.java:437)
	at org.picocontainer.DefaultPicoContainer.addAdapter(DefaultPicoContainer.java:458)
	at org.picocontainer.DefaultPicoContainer.addComponent(DefaultPicoContainer.java:555)
	at org.picocontainer.DefaultPicoContainer.addComponent(DefaultPicoContainer.java:500)
	at org.picocontainer.DefaultPicoContainer.addComponent(DefaultPicoContainer.java:487)
	at org.javers.core.AbstractJaversBuilder.addComponent(AbstractJaversBuilder.java:52)
	at org.javers.core.JaversBuilder.registerCustomComparator(JaversBuilder.java:302)
	at com.bee7.core.entityaudit.DatastoreEntityAuditerTest.<clinit>(DatastoreEntityAuditerTest.java:64)
	... 25 more*

Version used: 1.2.9

**Comment by bartoszwalacik** [comment]
fixed in 1.2.10
