### ISSUE TITLE
compare is not thread safe

### ISSUE THREAD

**Issue by fuhrmannm** [javers/javers#182]
Here is a stack-trace snippet:

java.util.ConcurrentModificationException: null
    at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429) ~[na:1.8.0_31]
    at java.util.HashMap$ValueIterator.next(HashMap.java:1458) ~[na:1.8.0_31]
    at org.javers.core.metamodel.type.TypeMapper.findNearestAncestor(TypeMapper.java:302) ~[javers-core-1.2.1.jar!/:na]
    at org.javers.core.metamodel.type.TypeMapper.infer(TypeMapper.java:276) ~[javers-core-1.2.1.jar!/:na]
    at org.javers.core.metamodel.type.TypeMapper.getJaversType(TypeMapper.java:106) ~[javers-core-1.2.1.jar!/:na]
    at org.javers.core.metamodel.type.TypeMapper.getPropertyType(TypeMapper.java:126) ~[javers-core-1.2.1.jar!/:na]
    at org.javers.core.metamodel.type.TypeMapper.isEntityReferenceOrValueObject(TypeMapper.java:130) ~[javers-core-1.2.1.jar!/:na]
    at org.javers.core.graph.ObjectGraphBuilder$1.apply(ObjectGraphBuilder.java:104) ~[javers-core-1.2.1.jar!/:na]
    at org.javers.core.graph.ObjectGraphBuilder$1.apply(ObjectGraphBuilder.java:102) ~[javers-core-1.2.1.jar!/:na]
    at org.javers.core.metamodel.clazz.ManagedClass.getProperties(ManagedClass.java:42) ~[javers-core-1.2.1.jar!/:na]
    at org.javers.core.graph.ObjectGraphBuilder.getSingleReferences(ObjectGraphBuilder.java:102) ~[javers-core-1.2.1.jar!/:na]
    at org.javers.core.graph.ObjectGraphBuilder.buildSingleEdges(ObjectGraphBuilder.java:72) ~[javers-core-1.2.1.jar!/:na]
    at org.javers.core.graph.ObjectGraphBuilder.buildEdges(ObjectGraphBuilder.java:67) ~[javers-core-1.2.1.jar!/:na]
    at org.javers.core.graph.ObjectGraphBuilder.buildGraph(ObjectGraphBuilder.java:55) ~[javers-core-1.2.1.jar!/:na]
    at org.javers.core.graph.LiveGraphFactory.createLiveGraph(LiveGraphFactory.java:28) ~[javers-core-1.2.1.jar!/:na]
    at org.javers.core.diff.DiffFactory.buildGraph(DiffFactory.java:90) ~[javers-core-1.2.1.jar!/:na]
    at org.javers.core.diff.DiffFactory.compare(DiffFactory.java:58) ~[javers-core-1.2.1.jar!/:na]
    at org.javers.core.JaversCore.compare(JaversCore.java:86) ~[javers-core-1.2.1.jar!/:na]
    ...

A possible fix could be to use ConcurrentHashmap for mappedTypes. Or to add a new thread-safe compare function that synchronizes around mappedTypes

**Comment by bartoszwalacik** [comment]
Right,  will change to concurrent hash map

**Comment by bartoszwalacik** [comment]
changed to ConcurrentHashMap, released in v1.3.1
http://search.maven.org/#search|ga|1|javers-core
