### ISSUE TITLE
Child entity inheriting from MappedSuperclass with @Id annotation fails

### ISSUE THREAD

**Issue by lfarmer** [javers/javers#185]
Hi Guys,

Got an issue whereby entities that inherit from a @MappedSuperclass which contains the @Id annotation, fail during a commit.

Here is the relevant stacktrace:

```
JaversException: ENTITY_WITHOUT_ID JaVers bootstrap error - Class '<ENTITY_NAME>' has no Id property. Use @Id annotation to mark unique Entity identifier
	at org.javers.core.metamodel.clazz.Entity.findDefaultIdProperty(Entity.java:39)
	at org.javers.core.metamodel.clazz.Entity.<init>(Entity.java:23)
	at org.javers.core.metamodel.clazz.ManagedClassFactory.create(ManagedClassFactory.java:92)
	at org.javers.core.metamodel.clazz.ManagedClassFactory.create(ManagedClassFactory.java:68)
	at org.javers.core.metamodel.clazz.ManagedClassFactory.inferFromAnnotations(ManagedClassFactory.java:48)
	at org.javers.core.metamodel.type.TypeFactory.inferFromAnnotations(TypeFactory.java:73)
	at org.javers.core.metamodel.type.TypeFactory.infer(TypeFactory.java:41)
	at org.javers.core.metamodel.type.TypeMapper.infer(TypeMapper.java:276)
	at org.javers.core.metamodel.type.TypeMapper.getJaversType(TypeMapper.java:107)
	at org.javers.core.metamodel.type.TypeMapper.getJaversManagedType(TypeMapper.java:114)
	at org.javers.core.metamodel.object.GlobalIdFactory.getManagedClassOf(GlobalIdFactory.java:98)
	at org.javers.core.metamodel.object.GlobalIdFactory.createId(GlobalIdFactory.java:39)
	at org.javers.core.graph.LiveCdoFactory.create(LiveCdoFactory.java:21)
	at org.javers.core.graph.EdgeBuilder.asCdo(EdgeBuilder.java:39)
	at org.javers.core.graph.ObjectGraphBuilder.buildGraph(ObjectGraphBuilder.java:47)
	at org.javers.core.graph.LiveGraphFactory.createLiveGraph(LiveGraphFactory.java:30)
	at org.javers.core.commit.CommitFactory.create(CommitFactory.java:75)
	at org.javers.core.JaversCore.commit(JaversCore.java:60)
	at org.javers.spring.jpa.JaversTransactionalDecorator.commit(JaversTransactionalDecorator.java:48)
	at org.javers.spring.auditable.aspect.JaversCommitAdvice.commitMethodArguments(JaversCommitAdvice.java:24)
```

**Comment by bartoszwalacik** [comment]
when your class has @javax.persistence.MappedSuperclass annotation, it is mapped as Entity by Javers. Entities should have ID's.

**Comment by lfarmer** [comment]
I seem to have resolved this issue by removing the @Id from the getter and placing it at field level
