### ISSUE TITLE
Commit fails on entity with overrided id getter having @Id annotation

### ISSUE THREAD

**Issue by 7erg** [javers/javers#346]
Hi,

I have an issue with inherited entity field with @Id annotation on overrided id getter during a commit.

Code sample:

```
public class MySuperEntity{
    private UUID id;
    public UUID getId() {
        return this.id;
    }
    public void setId(UUID id) {
        this.id = id;
    }
}

@Entity
@Table(name = "mytable")
public class MyEntity extends MySuperEntity{
    @Id
    @Column(name = "id")
    @Override
    public UUID getId() {
        return super.getId();
    }
}

```

Relevant stacktrace:

```
JaversException: ENTITY_WITHOUT_ID Class 'MyEntity' mapped as Entity has no Id property. Use @Id annotation to mark unique and not-null Entity identifier
	at org.javers.core.metamodel.type.EntityType.findDefaultIdProperty(EntityType.java:120)
	at org.javers.core.metamodel.type.EntityType.<init>(EntityType.java:45)
	at org.javers.core.metamodel.type.TypeFactory.createEntity(TypeFactory.java:68)
	at org.javers.core.metamodel.type.TypeFactory.create(TypeFactory.java:36)
	at org.javers.core.metamodel.type.TypeFactory.inferFromAnnotations(TypeFactory.java:136)
	at org.javers.core.metamodel.type.TypeFactory.infer(TypeFactory.java:81)
	at org.javers.core.metamodel.type.TypeMapperState.infer(TypeMapperState.java:161)
	at org.javers.core.metamodel.type.TypeMapperState.access$000(TypeMapperState.java:23)
	at org.javers.core.metamodel.type.TypeMapperState$1.apply(TypeMapperState.java:87)
	at org.javers.core.metamodel.type.TypeMapperState$1.apply(TypeMapperState.java:85)
	at org.javers.core.metamodel.type.TypeMapperState.computeIfAbsent(TypeMapperState.java:118)
	at org.javers.core.metamodel.type.TypeMapperState.getJaversType(TypeMapperState.java:85)
	at org.javers.core.metamodel.type.TypeMapper.getJaversType(TypeMapper.java:103)
	at org.javers.core.metamodel.type.TypeMapper.getPropertyType(TypeMapper.java:167)
	at org.javers.core.graph.ObjectGraphBuilder$1.apply(ObjectGraphBuilder.java:108)
	at org.javers.core.graph.ObjectGraphBuilder$1.apply(ObjectGraphBuilder.java:106)
	at org.javers.core.metamodel.type.ManagedClass.getManagedProperties(ManagedClass.java:60)
	at org.javers.core.metamodel.type.ManagedType.getProperties(ManagedType.java:49)
	at org.javers.core.graph.ObjectGraphBuilder.getSingleReferencesWithManagedTypes(ObjectGraphBuilder.java:106)
	at org.javers.core.graph.ObjectGraphBuilder.buildSingleEdges(ObjectGraphBuilder.java:76)
	at org.javers.core.graph.ObjectGraphBuilder.buildEdges(ObjectGraphBuilder.java:71)
	at org.javers.core.graph.ObjectGraphBuilder.buildGraphFromCdo(ObjectGraphBuilder.java:59)
	at org.javers.core.graph.ObjectGraphBuilder.buildGraph(ObjectGraphBuilder.java:48)
	at org.javers.core.graph.LiveGraphFactory.createLiveGraph(LiveGraphFactory.java:39)
	at org.javers.core.commit.CommitFactory.create(CommitFactory.java:76)
	at org.javers.core.JaversCore.commit(JaversCore.java:70)
	at org.javers.spring.auditable.aspect.OnSaveAuditChangeHandler.handle(OnSaveAuditChangeHandler.java:17)
	at org.javers.spring.auditable.aspect.JaversAuditableRepositoryAspect.applyVersionChange(JaversAuditableRepositoryAspect.java:93)
	at org.javers.spring.auditable.aspect.JaversAuditableRepositoryAspect.applyVersionChanges(JaversAuditableRepositoryAspect.java:88)
	at org.javers.spring.auditable.aspect.JaversAuditableRepositoryAspect.onVersionEvent(JaversAuditableRepositoryAspect.java:70)
	at org.javers.spring.auditable.aspect.JaversAuditableRepositoryAspect.onSaveExecuted(JaversAuditableRepositoryAspect.java:58)
```

I have found a similar closed [issue](https://github.com/javers/javers/issues/185), but I have no `@MappedSuperclass`, so it should work in my opinion.

I'm using version 1.5.1

**Comment by bartoszwalacik** [comment]
I will take a look , did you set mapping style to BEAN?

**Comment by 7erg** [comment]
I can't use it, because it is not all my beans using this style, most of them has annotations on fields...
5 марта 2016 г. 11:31 PM пользователь Bartosz Walacik <notifications@github.com> написал:I will take a look , did you set mapping style to BEAN?

**Comment by bartoszwalacik** [comment]
If you are using FIELD mapping  style , you need to put @Id ann on field. Alternatively you can map classes explicitly using JaversBuilder.register... methods

**Comment by bartoszwalacik** [comment]
JaversBuilder.register has priority over annotations

**Comment by 7erg** [comment]
I tried the code below and it works for me! Thank you, bartoszwalacik!

```
JaversBuilder.javers()
...
.registerEntity(new EntityDefinition(MyEntity.class, "id"))
....
```
