### ISSUE TITLE
2.0.1 does not support fastutil Int2ObjectMap

### ISSUE THREAD

**Issue by pranasblk** [javers/javers#390]
Java
```
public class NotSupportedObject {
  final AttributeMetaContainer c = new AttributeMetaContainer(new DynamicPool<>(ByteSegment.class, ByteSegment::new));
}
```

Field in the AttributeMetaContainer:
```
  private final Int2ObjectMap<ByteSegment> attributes;
```

Groovy check:
```
    NotSupportedObject testObjet = new NotSupportedObject();
    Javers javers = JaversBuilder.javers().build()
    Diff diff = javers.compare(testObjet, testObjet)
    assert diff.changes.isEmpty()
```

Result:
```
Exception in thread "main" JaversException: VALUE_OBJECT_IS_NOT_SUPPORTED_AS_MAP_KEY found ValueObject on KEY position in Map property 'MapType{baseType:'it.unimi.dsi.fastutil.ints.Int2ObjectMap<xxx.ByteSegment>'}'. Please change the key class mapping to Value or Entity
	at org.javers.core.diff.appenders.MapChangeAppender.supports(MapChangeAppender.java:43)
	at org.javers.core.diff.DiffFactory.appendChanges(DiffFactory.java:156)
	at org.javers.core.diff.DiffFactory.appendPropertyChanges(DiffFactory.java:150)
	at org.javers.core.diff.DiffFactory.createAndAppendChanges(DiffFactory.java:132)
	at org.javers.core.diff.DiffFactory.create(DiffFactory.java:78)
	at org.javers.core.diff.DiffFactory.compare(DiffFactory.java:63)
	at org.javers.core.JaversCore.compare(JaversCore.java:121)
	at org.javers.core.Javers$compare.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:133)
	at xxx.TestDiff.main(TestDiff.groovy:15)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
```

The issue with MapChangeAppender getting incorrect model. 
The key type is **primitive int** and not **ValueObject**.

**Comment by pranasblk** [comment]
I propose to remove such implementation specific validation - there are plenty of Map implementations using only one generic parameter e.g. koloboke, trove, fastutils ... 

Dziękuję bardzo!

**Comment by bartoszwalacik** [comment]
JaVers depends only on Map interface and not concrete Map implementations. The problem could be that JaVers doesn't recognize this Map key type as Integer. That's interesting case, could you push complete, failing test for this issue? Could be on your JaVers fork.

**Comment by bartoszwalacik** [comment]
closing due to lack of activity
