### ISSUE TITLE
Problem with committing map with ValueObject as a key

### ISSUE THREAD

**Issue by mstrojny** [javers/javers#404]
Hi!

I am unable to commit an object, which has a Map field, if this map's keys are resolved as ValueObject. I get this exception:

> JaversException: VALUE_OBJECT_IS_NOT_SUPPORTED_AS_MAP_KEY found ValueObject on KEY position in Map property

However, in my case I cannot map the key as Value or Entity. Actually the objects I want commit in runtime are unknown during implementation - any object may be the key. Registering of all the mappings a priori is not possible.
I also tried to _JaversBuilder.javers().registerIgnoredClass(Map.class)_ but it did not work as well.

Is it possible to make javers ignore (only) such maps? Any other suggestions how to use javers in my circumstances? The exception which is thrown makes it impossible to store such objects at all:

```
JaversException: VALUE_OBJECT_IS_NOT_SUPPORTED_AS_MAP_KEY found ValueObject on KEY position in Map property 'MapType{baseType:'java.util.Map<examples.values.TrackableMethodExample$ResultStatus, java.util.List<java.lang.String>>'}'. Please change the key class mapping to Value or Entity
	at org.javers.core.diff.appenders.MapChangeAppender.supports(MapChangeAppender.java:43)
	at org.javers.core.diff.DiffFactory.appendChanges(DiffFactory.java:156)
	at org.javers.core.diff.DiffFactory.appendPropertyChanges(DiffFactory.java:150)
	at org.javers.core.diff.DiffFactory.createAndAppendChanges(DiffFactory.java:132)
	at org.javers.core.diff.DiffFactory.create(DiffFactory.java:78)
	at org.javers.core.commit.CommitFactory.create(CommitFactory.java:70)
	at org.javers.core.JaversCore.commit(JaversCore.java:77)
```

Thank you,
Marcin

**Comment by bartoszwalacik** [comment]
just ignore this Map field with `@DiffIgnore`
see http://javers.org/documentation/domain-configuration/#ignoring-things
