### ISSUE TITLE
Javers V3.0.0: While calling compare method to compare 2-complex objects getting error java.lang.IllegalArgumentException: argument should not be null

### ISSUE THREAD

**Issue by poornendusharma** [javers/javers#498]
java.lang.IllegalArgumentException: argument should not be null
	at org.javers.common.validation.Validate.argumentsAreNotNull(Validate.java:33)
	at org.javers.core.metamodel.object.GlobalIdFactory.createId(GlobalIdFactory.java:43)
	at org.javers.core.graph.LiveCdoFactory.create(LiveCdoFactory.java:25)
	at org.javers.core.graph.LiveCdoFactory.create(LiveCdoFactory.java:10)
	at org.javers.core.graph.EdgeBuilder$MultiEdgeContainerBuilderFunction.apply(EdgeBuilder.java:78)
	at org.javers.core.metamodel.type.ArrayType.map(ArrayType.java:44)
	at org.javers.core.graph.EdgeBuilder.createMultiEdge(EdgeBuilder.java:61)
	at org.javers.core.graph.ObjectGraphBuilder.buildMultiEdges(ObjectGraphBuilder.java:92)
	at org.javers.core.graph.ObjectGraphBuilder.buildEdges(ObjectGraphBuilder.java:72)
	at org.javers.core.graph.ObjectGraphBuilder.buildGraphFromCdo(ObjectGraphBuilder.java:59)
	at org.javers.core.graph.ObjectGraphBuilder.buildGraph(ObjectGraphBuilder.java:48)
	at org.javers.core.graph.LiveGraphFactory.createLiveGraph(LiveGraphFactory.java:39)
	at org.javers.core.diff.DiffFactory.buildGraph(DiffFactory.java:101)
	at org.javers.core.diff.DiffFactory.compare(DiffFactory.java:56)
	at org.javers.core.JaversCore.compare(JaversCore.java:127)

**Comment by bartoszwalacik** [comment]
and a test case with the reproduction scenario?

**Comment by poornendusharma** [comment]
Thanks for the quick response. While using object.clone() in the method it's working fine. Only incase of directly using object in compare method it throws the IllegalArgument exception. Sorry but test case with reproduction scenario is not feasible.

**Comment by bartoszwalacik** [comment]
ok, so how do I reproduce this issue on my computer?

**Comment by bartoszwalacik** [comment]
I cant start work without a reproduction scenario. Closing due to lack of activity
