### ISSUE TITLE
IndexOutOfBoundsException (v3.0.4)

### ISSUE THREAD

**Issue by nmihajlovski** [javers/javers#523]
```
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at java.util.Collections$UnmodifiableList.get(Collections.java:1309)
	at org.javers.repository.sql.finders.CdoSnapshotFinder.lambda$getLatest$1(CdoSnapshotFinder.java:54)
	at org.javers.repository.sql.finders.CdoSnapshotFinder.getLatest(CdoSnapshotFinder.java:52)
	at org.javers.repository.sql.JaversSqlRepository.getLatest(JaversSqlRepository.java:46)
	at org.javers.repository.api.JaversExtendedRepository.getLatest(JaversExtendedRepository.java:81)
	at org.javers.core.snapshot.GraphShadowFactory.createLatestShadow(GraphShadowFactory.java:29)
	at org.javers.core.snapshot.GraphSnapshotFacade.createLatestShadow(GraphSnapshotFacade.java:22)
	at org.javers.core.commit.CommitFactory.create(CommitFactory.java:68)
	at org.javers.core.JaversCore.commit(JaversCore.java:80)
	at org.javers.spring.jpa.JaversTransactionalDecorator.commit(JaversTransactionalDecorator.java:63)
	at org.javers.spring.jpa.JaversTransactionalDecorator$$FastClassBySpringCGLIB$$acb40bd0.invoke(<generated>)
	at org.javers.spring.jpa.JaversTransactionalDecorator$$EnhancerBySpringCGLIB$$7578d67f.commit(<generated>)
	at org.javers.spring.auditable.aspect.springdata.OnSaveAuditChangeHandler.handle(OnSaveAuditChangeHandler.java:18)
	at org.javers.spring.auditable.aspect.springdata.JaversSpringDataAuditableRepositoryAspect.applyVersionChange(JaversSpringDataAuditableRepositoryAspect.java:80)
	at org.javers.spring.auditable.aspect.springdata.JaversSpringDataAuditableRepositoryAspect.applyVersionChanges(JaversSpringDataAuditableRepositoryAspect.java:75)
	at org.javers.spring.auditable.aspect.springdata.JaversSpringDataAuditableRepositoryAspect.lambda$onVersionEvent$0(JaversSpringDataAuditableRepositoryAspect.java:56)
	at org.javers.spring.auditable.aspect.springdata.JaversSpringDataAuditableRepositoryAspect.onVersionEvent(JaversSpringDataAuditableRepositoryAspect.java:53)
	at org.javers.spring.auditable.aspect.springdata.JaversSpringDataAuditableRepositoryAspect.onSaveExecuted(JaversSpringDataAuditableRepositoryAspect.java:47)

```

**Comment by bartoszwalacik** [comment]
@nmihajlovski, bug report should contain a reproduction scenario. Isn't it obvious that having only a fragment of the stack trace doesn't help me much?

**Comment by nmihajlovski** [comment]
The exception gets thrown at:
`return fetchCdoSnapshots(new SnapshotIdFilter(tableNameProvider, maxSnapshot), Optional.of(oneItemLimit)).get(0);`

Basically, `fetchCdoSnapshots` returns empty list, so `get(0)` fails. Is this expected behavior? If so, I suggest adding some assertions here, Libraries shouldn't just throw `IndexOutOfBoundsException` or `NullPointerException`, instead more meaningful errors are expected.

We will try to provide a way to isolate and reproduce the bug...

**Comment by igslznev** [comment]
Had same problem, after looking at source code can say, that **IndexOutOfBoundsException** happens when you try to rerun your application and first action (in my case) is trying to view audit change detail. 

Want you to notice, that in this case in `javers/javers-persistence-sql/src/main/java/org/javers/repository/sql/repositories/GlobalIdRepository.java` in this method: 

```
    public Optional<Long> findGlobalIdPk(GlobalId globalId) {
        if (disableCache){
            return findGlobalIdPkInDB(globalId);
        }

        Long foundPk = globalIdPkCache.getIfPresent(globalId);

        if (foundPk != null){
            return Optional.of(foundPk);
        }

        Optional<Long> fresh = findGlobalIdPkInDB(globalId);
        if (fresh.isPresent()){
            globalIdPkCache.put(globalId, fresh.get());
        }

        return fresh;
    }
```
Instead of taking value from cache it goes to `findGlobalIdPkInDB(globalId)` method as you can see. This information is for recreation purposes.

So the problem is in `jsonConverter.toJson(((InstanceId)globalId).getCdoId())` in this section of `findGlobalIdPkInDB(globalId)` method (don't know about other cases).
```
//...
 else if (globalId instanceof InstanceId){
            query
                .where(GLOBAL_ID_LOCAL_ID + " = :localId ")
                .withArgument("localId", jsonConverter.toJson(((InstanceId)globalId).getCdoId()))
                .append("AND " + GLOBAL_ID_TYPE_NAME + " = :qualifiedName ")
                .withArgument("qualifiedName", globalId.getTypeName());
        }
//...
```
Argument `localId` is becomes like, for example, `""1111""` instead of `"1111"` so querying DB returns nothing. I think that `jsonConverter.toJson(((InstanceId)globalId).getCdoId())` causes it and it must be replaced with just `globalId.getCdoId()` to prevent problem so it looks like this:
```
//...
query
    .where(GLOBAL_ID_LOCAL_ID + " = :localId ")
    .withArgument("localId", globalId.getCdoId())
    .append("AND " + GLOBAL_ID_TYPE_NAME + " = :qualifiedName ")
    .withArgument("qualifiedName", globalId.getTypeName());
//...
```

I am using PostgreSQL DB, if it might help to resolve this problem.

**Comment by bartoszwalacik** [comment]
it cant be just `globalId.getCdoId()` because it has to be the same String value which is inserted, see GlobalIdRepository line 117

Still, waiting for the reproduction scenario. Failing test case would be perfect

**Comment by bartoszwalacik** [comment]
The root cause could be for example data corruption in your DB. For example when some snapshots were deleted without deleting corresponding globalId records

**Comment by nmihajlovski** [comment]
We tried few times with a clean database (dropped the 4 jv_*) tables, and the exception occurred for a small percentage of the updates at each attempt. Suspecting this might be due to some race condition (e.g. on database or cache level), we are going to try again today (using v3.1.0) without concurrent updates.

**Comment by bartoszwalacik** [comment]
race condition is a good clue, please keep digging

**Comment by nmihajlovski** [comment]
As suspected, when updating with only 1 thread this problem doesn't occur.

**Comment by bartoszwalacik** [comment]
that's interesting, could you reproduce it? We have a good test for concurrent writes ... https://github.com/javers/javers/blob/master/javers-persistence-sql/src/test/groovy/org/javers/repository/sql/JaversSqlRepositoryConcurrentWriteTest.groovy

**Comment by bartoszwalacik** [comment]
I've run this test for all databases, and it failed on MySql - https://travis-ci.org/javers/javers/builds/217269557

**Comment by nmihajlovski** [comment]
We are using MySQL, too. Today I didn't manage to reproduce the bug using simple experiments.

**Comment by bartoszwalacik** [comment]
still, cant reproduce

**Comment by bartoszwalacik** [comment]
please reopen if you be able to reproduce this issue
