### ISSUE TITLE
Null list item causes failure

### ISSUE THREAD

**Issue by shollander** [javers/javers#676]
I am using Javers with MongoDB. I have an object with a field that is a `List`. If the `List` contains an entry that is `null`, then I get the following exception:
```
java.lang.IllegalArgumentException: argument should not be null
    at org.javers.common.validation.Validate.argumentsAreNotNull(Validate.java:33)
    at org.javers.core.metamodel.object.GlobalIdFactory.createId(GlobalIdFactory.java:44)
    at org.javers.core.graph.LiveCdoFactory.create(LiveCdoFactory.java:29)
    at org.javers.core.graph.LiveCdoFactory.create(LiveCdoFactory.java:15)
    at org.javers.core.graph.EdgeBuilder$MultiEdgeContainerBuilderFunction.apply(EdgeBuilder.java:72)
    at org.javers.core.metamodel.type.ListType.map(ListType.java:33)
    ...
```

**Comment by shollander** [comment]
If I have a domain object like this:
```java
@Document
public class Customer {
    @Id
    private String id;
    private List<Order> orders;

    // getters/setters
}
```
```java
public class Order {
    private String orderNumber;

   // getters/setters
}
```

Then this test will fail with an exception:
```java
@SpringJUnitConfig
@SpringBootTest
class CustomerTest {
    @Autowired
    CustomerRepository customerRepository;
    
    @Test
    void test() {
        Customer customer = new Customer();
        customer.setOrders(Arrays.asList(null, null));
        customerRepository.save(customer);
    }    
}
```
