### ISSUE TITLE
Cannot register custom comparator for List

### ISSUE THREAD

**Issue by kucharzyk** [javers/javers#714]
I want to override javers collection comparator.

I've tried to register custom comparator for List.class like this:

```
TransactionalJaversBuilder
            .javers()
            .withTxManager(transactionManager)
            .registerJaversRepository(sqlRepository)
            .withObjectAccessHook(new HibernateUnproxyObjectAccessHook())
            .withProperties(javersSqlProperties)
            .withListCompareAlgorithm(ListCompareAlgorithm.LEVENSHTEIN_DISTANCE)
            .registerCustomComparator((left, right, affectedId, property) -> {
                System.out.println("WHATEVER");
                return null;
            }, List.class)
            .build();
```

Unfortunatelly I've got the following exception (my comparator is never invoked - exception is thrown before)

`
java.lang.ArrayIndexOutOfBoundsException: 0

	at com.google.gson.internal.$Gson$Types.resolveTypeVariable($Gson$Types.java:430)
	at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:352)
	at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:381)
	at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:337)
	at com.google.gson.internal.$Gson$Types.getSupertype($Gson$Types.java:283)
	at com.google.gson.internal.$Gson$Types.getCollectionElementType($Gson$Types.java:302)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory.create(CollectionTypeAdapterFactory.java:52)
	at com.google.gson.Gson.getAdapter(Gson.java:458)
	at com.google.gson.Gson.fromJson(Gson.java:926)
	at com.google.gson.Gson.fromJson(Gson.java:994)
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162)
	at org.javers.core.json.typeadapter.commit.CdoSnapshotStateDeserializer.decodePropertyValue(CdoSnapshotStateDeserializer.java:66)
	at org.javers.core.json.typeadapter.commit.CdoSnapshotStateDeserializer.lambda$deserialize$0(CdoSnapshotStateDeserializer.java:38)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
	at org.javers.core.json.typeadapter.commit.CdoSnapshotStateDeserializer.deserialize(CdoSnapshotStateDeserializer.java:36)
	at org.javers.core.json.typeadapter.commit.CdoSnapshotTypeAdapter.deserializeSnapshotState(CdoSnapshotTypeAdapter.java:72)
	at org.javers.core.json.typeadapter.commit.CdoSnapshotTypeAdapter.fromJson(CdoSnapshotTypeAdapter.java:58)
	at org.javers.core.json.typeadapter.commit.CdoSnapshotTypeAdapter.fromJson(CdoSnapshotTypeAdapter.java:22)
	at org.javers.core.json.JsonConverterBuilder.lambda$registerJsonTypeAdapterForType$4(JsonConverterBuilder.java:168)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
	at com.google.gson.Gson.fromJson(Gson.java:927)
	at com.google.gson.Gson.fromJson(Gson.java:994)
	at com.google.gson.Gson.fromJson(Gson.java:967)
	at org.javers.core.json.JsonConverter.fromJson(JsonConverter.java:74)
	at org.javers.core.json.JsonConverter.fromSerializedSnapshot(JsonConverter.java:82)
	at org.javers.repository.sql.finders.CdoSnapshotFinder.lambda$fetchCdoSnapshots$3(CdoSnapshotFinder.java:94)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1492)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at org.javers.common.collections.Lists.transform(Lists.java:68)
	at org.javers.repository.sql.finders.CdoSnapshotFinder.fetchCdoSnapshots(CdoSnapshotFinder.java:93)
	at org.javers.repository.sql.finders.CdoSnapshotFinder.lambda$getStateHistory$2(CdoSnapshotFinder.java:81)
	at java.base/java.util.Optional.map(Optional.java:254)
	at org.javers.repository.sql.finders.CdoSnapshotFinder.getStateHistory(CdoSnapshotFinder.java:80)
	at org.javers.repository.sql.JaversSqlRepository.getStateHistory(JaversSqlRepository.java:96)
	at org.javers.repository.api.JaversExtendedRepository.getStateHistory(JaversExtendedRepository.java:71)
	at org.javers.repository.jql.SnapshotQueryRunner.queryForSnapshots(SnapshotQueryRunner.java:37)
	at org.javers.repository.jql.QueryRunner.queryForSnapshots(QueryRunner.java:44)
	at org.javers.core.JaversCore.findSnapshots(JaversCore.java:153)
	at org.javers.spring.jpa.JaversTransactionalDecorator.findSnapshots(JaversTransactionalDecorator.java:136)
	at org.javers.spring.jpa.JaversTransactionalDecorator$$FastClassBySpringCGLIB$$acb40bd0.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:746)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:294)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
	at org.javers.spring.jpa.JaversTransactionalDecorator$$EnhancerBySpringCGLIB$$87d089fa.findSnapshots(<generated>)

`

Custom comparator like this worked with old version of Javers.

Is this still possible to use it? 

I want to override algorithm used to compare lists of value objects

**Comment by bartoszwalacik** [comment]
could you please push a failing test case to github? 
see how it can be done - https://github.com/javers/javers/pull/713

**Comment by bartoszwalacik** [comment]
thnx @kucharzyk

**Comment by bartoszwalacik** [comment]
You can't register custom comparator for List, but you can register custom comparator for List items, see https://javers.org/documentation/domain-configuration/#ValueType
