### ISSUE TITLE
javers issue

### ISSUE THREAD

**Issue by charan9898** [javers/javers#722]
Hi iam using Javers for testing and i have encountered below error
-------------------------------------------------------------------------------------
Exception in thread "main" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.javers.common.reflection.ReflectionUtil.newInstance(ReflectionUtil.java:91)
	at org.javers.core.pico.InstantiatingModule$ConstructorInjector.getComponentInstance(InstantiatingModule.java:48)
	at org.picocontainer.behaviors.AbstractBehavior.getComponentInstance(AbstractBehavior.java:64)
	at org.picocontainer.behaviors.Stored.getComponentInstance(Stored.java:91)
	at org.picocontainer.DefaultPicoContainer.getInstance(DefaultPicoContainer.java:699)
	at org.picocontainer.DefaultPicoContainer.getComponent(DefaultPicoContainer.java:647)
	at org.picocontainer.DefaultPicoContainer.getComponent(DefaultPicoContainer.java:678)
	at org.javers.core.AbstractContainerBuilder.getContainerComponent(AbstractContainerBuilder.java:22)
	at org.javers.core.JaversBuilder.typeMapper(JaversBuilder.java:500)
	at org.javers.core.JaversBuilder.mapRegisteredClasses(JaversBuilder.java:493)
	at org.javers.core.JaversBuilder.bootManagedTypeModule(JaversBuilder.java:513)
	at org.javers.core.JaversBuilder.assembleJaversInstance(JaversBuilder.java:119)
	at org.javers.core.JaversBuilder.build(JaversBuilder.java:106)
	at Employee.main(Employee.java:34)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.javers.common.reflection.ReflectionUtil.newInstance(ReflectionUtil.java:89)
	... 13 more
Caused by: java.lang.NoClassDefFoundError: org/joda/time/LocalDateTime
	at org.javers.core.metamodel.type.TypeMapper.registerCoreTypes(TypeMapper.java:64)
	at org.javers.core.metamodel.type.TypeMapper.<init>(TypeMapper.java:37)
	... 18 more
Caused by: java.lang.ClassNotFoundException: org.joda.time.LocalDateTime
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 20 more
--------------------------------------------------------------------------------------------------
Below is my code:

--------------------------------------------------------
import org.javers.core.Javers;
import org.javers.core.JaversBuilder;
import org.javers.core.diff.Diff;
import org.javers.core.metamodel.annotation.Id;
import org.javers.core.metamodel.annotation.TypeName;
public class Employee {
private String name;
@Id
private int rno;

public Employee() {
	// TODO Auto-generated constructor stub
}

public void setRno(int rno)
{
	this.rno=rno;
}

public void setName(String name)
{
	this.name=name;
}
public static void main(String[] args) {
Javers javers;	// TODO Auto-generated method stub
	Employee emp1=new Employee();

		Employee emp2 =new Employee();
		Employee emp=new Employee();
		emp1.setName("abc");
		emp2.setName("xyz");
		emp1.setRno(1);
		emp2.setRno(1);
		javers = JaversBuilder.javers().build();
		Diff diff=javers.compare(emp1, emp2);
		System.out.println(diff.changesSummary());
}
}
----------------------------------------------------------------------------------------------

**Comment by bartoszwalacik** [comment]
### looks like a classpath problem on your side, it you still think that you found a bug in javers, follow 
**guidelines  for bug reporting**

https://github.com/javers/javers/blob/master/CONTRIBUTING.md#guidelines-for-bug-reporting

**Comment by charan9898** [comment]
if its a classpath issue....any suggestions on how to fix it..?

**Comment by bartoszwalacik** [comment]
Take a look at javers code:
https://github.com/javers/javers/blob/612267b2318d83a384ba37b7a1e15119a88c3f8f/javers-core/src/main/java/org/javers/core/JaversBuilder.java#L107
joda type adapters are loaded because you **have** `org.joda.time.LocalDate` on your classpath.
I don't know why you don't have `org.joda.time.LocalDateTime`

**Comment by charan9898** [comment]
Yeah i added joda jar files ... the issue was fixed..
