### ISSUE TITLE
regression 3.13.0 duplicate key value violates unique constraint "jv_commit_pk"

### ISSUE THREAD

**Issue by pethers** [javers/javers#736]
When updating from 3.12.4 and start to get below exception, any changes required after updating ? 

     [exec] org.javers.common.exception.JaversException: SQL_EXCEPTION: ERROR: duplicate key value violates unique constraint "jv_commit_pk"
     [exec]   Detail: Key (commit_pk)=(38795) already exists.
     [exec] while executing sql: INSERT INTO jv_commit ( author, commit_date, commit_id, commit_pk ) VALUES  ( ?,?,?,? )
     [exec] 	at org.javers.repository.sql.session.PreparedStatementExecutor.wrapExceptionAndCall(PreparedStatementExecutor.java:120)
     [exec] 	at org.javers.repository.sql.session.PreparedStatementExecutor.runVoidSql(PreparedStatementExecutor.java:110)
     [exec] 	at org.javers.repository.sql.session.PreparedStatementExecutor.execute(PreparedStatementExecutor.java:39)
     [exec] 	at org.javers.repository.sql.session.Session.execute(Session.java:105)
     [exec] 	at org.javers.repository.sql.session.Session.executeInsertAndGetSequence(Session.java:51)
     [exec] 	at org.javers.repository.sql.session.InsertBuilder.executeAndGetSequence(InsertBuilder.java:54)
     [exec] 	at org.javers.repository.sql.repositories.CommitMetadataRepository.insertCommit(CommitMetadataRepository.java:45)
     [exec] 	at org.javers.repository.sql.repositories.CommitMetadataRepository.save(CommitMetadataRepository.java:33)
     [exec] 	at org.javers.repository.sql.JaversSqlRepository.persist(JaversSqlRepository.java:93)
     [exec] 	at org.javers.repository.api.JaversExtendedRepository.persist(JaversExtendedRepository.java:154)
     [exec] 	at org.javers.core.JaversCore.persist(JaversCore.java:104)
     [exec] 	at org.javers.core.JaversCore.commit(JaversCore.java:85)
     [exec] 	at org.javers.spring.jpa.JaversTransactionalDecorator.commit(JaversTransactionalDecorator.java:83)
     [exec] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec] 	at java.lang.reflect.Method.invoke(Method.java:498)
     [exec] 	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
     [exec] 	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
     [exec] 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
     [exec] 	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:294)
     [exec] 	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98)
     [exec] 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
     [exec] 	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
     [exec] 	at com.sun.proxy.$Proxy285.commit(Unknown Source)
     [exec] 	at org.javers.spring.auditable.aspect.JaversCommitAdvice.commitMethodArguments(JaversCommitAdvice.java:31)
     [exec] 	at org.javers.spring.auditable.aspect.JaversAuditableAspect.commitAdvice(JaversAuditableAspect.java:37)
     [exec] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec] 	at java.lang.reflect.Method.invoke(Method.java:498)
     [exec] 	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:644)
     [exec] 	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:626)
     [exec] 	at org.springframework.aop.aspectj.AspectJAfterReturningAdvice.afterReturning(AspectJAfterReturningAdvice.java:66)
     [exec] 	at org.springframework.aop.framework.adapter.AfterReturningAdviceInterceptor.invoke(AfterReturningAdviceInterceptor.java:56)
     [exec] 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
     [exec] 	at net.bull.javamelody.MonitoringSpringInterceptor.invoke(MonitoringSpringInterceptor.java:76)
     [exec] 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
     [exec] 	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:93)
     [exec] 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
     [exec] 	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
     [exec] 	at com.sun.proxy.$Proxy205.persist(Unknown Source)
     [exec] 	at sun.reflect.GeneratedMethodAccessor444.invoke(Unknown Source)
     [exec] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec] 	at java.lang.reflect.Method.invoke(Method.java:498)
     [exec] 	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
     [exec] 	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
     [exec] 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
     [exec] 	at net.bull.javamelody.MonitoringSpringInterceptor.invoke(MonitoringSpringInterceptor.java:76)
     [exec] 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
     [exec] 	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
     [exec] 	at com.sun.proxy.$Proxy206.persist(Unknown Source)
     [exec] 	at com.hack23.cia.service.impl.action.application.CreateApplicationSessionService.processService(CreateApplicationSessionService.java:81)

**Comment by bartoszwalacik** [comment]
thanks for reporting, looks like a problem with sequence allocation. I will check it

**Comment by pethers** [comment]
Thanks for providing a great framework, happy to help out with test it if you find anything.

**Comment by bartoszwalacik** [comment]
ok, 3.13.0 needs to be fixed, there is a bug in sequence allocation

**Comment by pethers** [comment]
Excellent it works :)
