### ISSUE TITLE
Thread Safety problems

### ISSUE THREAD

**Issue by mniedobecki** [javers/javers#755]
hi Javers-Team,

with the latest version 3.14.0 I have still problem using Javers in multithreaded environment. I have read about some problems in the previous threads but I thought all of them are solved.

In my case:
1.) I use one instance of Javers class across multiple threads.
2.) multiple threads can call the compare method for exactly the same object.

and get following exception:

Caused by: java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
	at java.util.ArrayList$Itr.next(ArrayList.java:851)
	at org.javers.core.metamodel.type.ListType.map(ListType.java:32)
	at org.javers.core.graph.EdgeBuilder.createMultiEdge(EdgeBuilder.java:55)
	at org.javers.core.graph.ObjectGraphBuilder.buildMultiEdges(ObjectGraphBuilder.java:91)
	at org.javers.core.graph.ObjectGraphBuilder.buildEdges(ObjectGraphBuilder.java:71)
	at org.javers.core.graph.ObjectGraphBuilder.buildGraphFromCdo(ObjectGraphBuilder.java:58)
	at org.javers.core.graph.ObjectGraphBuilder.buildGraph(ObjectGraphBuilder.java:47)
	at org.javers.core.graph.LiveGraphFactory.createLiveGraph(LiveGraphFactory.java:39)
	at org.javers.core.diff.DiffFactory.buildGraph(DiffFactory.java:99)
	at org.javers.core.diff.DiffFactory.compare(DiffFactory.java:54)
	at org.javers.core.JaversCore.compare(JaversCore.java:173)

Could please help ? 
many thanks in advance !

**Comment by bartoszwalacik** [comment]
Hi, thanks for reporting, looks like the exception is thrown when JaVers tries to iterate over one of your Lists.  Is it possible that one of your threads is writing to this list while another thread is doing javers.compare on it?

**Comment by mniedobecki** [comment]
hi,
sorry for a late answer. I have double checked my code and it seems that all my objects are not being modified at the point when calling compare. I will try to reproduce this via unit test.
cheers
Marcin

**Comment by mniedobecki** [comment]
yes, this is not the issue of the Javers but issue in our implementation. Therefore we decided to perform deep copy of objects before calling compare to avoid this kind of exception.
Thanks !

**Comment by bartoszwalacik** [comment]
ok
