### ISSUE TITLE
Error saving new field "COMMIT_DATE_INSTANT" and creating tables on version 5.1.0

### ISSUE THREAD

**Issue by NicoBondarenco** [javers/javers#765]
After the new version (5.1.0), when I use SQLRepository, Javers creates the new field on database like "commit_date_instant varchar(26) DEFAULT NULL" but when I try to call the commit method, I get an error saying:
"JaversException SQL_EXCEPTION: Value too long for column "COMMIT_DATE_INSTANT VARCHAR(26)": "'2019-01-04T11:36:23.572228100Z' (30)"; SQL statement:
INSERT INTO jv_commit ( author, commit_date, commit_date_instant, commit_id, commit_pk ) VALUES  ( ?,?,?,?,? ) [22001-197]
while executing sql: INSERT INTO jv_commit ( author, commit_date, commit_date_instant, commit_id, commit_pk ) VALUES  ( ?,?,?,?,? )"

Looking in the code, I saw that the "COMMIT_DATE_INSTANT" value is formatted to a String using "DateTimeFormatter.ISO_INSTANT.format(dateInstant)" (org.javers.repository.sql.repositories.CommitMetadataRepository:40). This is generating a String(30).

Is it possible to leave this "DateTimeFormatter.ISO_INSTANT" as a default and create a configuration to format this field? Or alter the column generation to a larger length?

BTW: I'm using Javers with H2 for unit tests. I also tried to use MySQL and got the same problem.

Another thing is, if I'm using Hibernate configuration "hibernate.hbm2ddl.auto" as validate and the tables are already created, Javers is trying to create the tables again on JaversBuilder.build(), then I get an error saying that the tables already exists.

**Comment by NicoBondarenco** [comment]
My Java version is
java 10.0.2 2018-07-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.2+13)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.2+13, mixed mode)

I don't know if could be it, but maybe the region? I'm from Brazil.

I tried to use a custom provider too, and got the same problem. (.withDateTimeProvider(() -> ZonedDateTime.now(ZoneOffset.UTC)))

jshell> ZonedDateTime.now()
$2 ==> 2019-01-04T14:29:27.824778400-02:00[America/Sao_Paulo]

jshell> ZonedDateTime.now().toInstant()
$3 ==> 2019-01-04T16:29:51.205005500Z

**Comment by bartoszwalacik** [comment]
looks like java 10 creates Instant.now() with nano precision while java 8 creats with millis precision. I will fix it

**Comment by NicoBondarenco** [comment]
Thanks very much

**Comment by NicoBondarenco** [comment]
Still getting the same error, and I'm getting some other errors too.

`JaversException SQL_EXCEPTION: Value too long for column "COMMIT_DATE_INSTANT VARCHAR(26)": "'2019-01-05T21:31:38.881609100Z' (30)"; SQL statement:
INSERT INTO jv_commit ( author, commit_date, commit_date_instant, commit_id, commit_pk ) VALUES  ( ?,?,?,?,? ) [22001-197]
while executing sql: INSERT INTO jv_commit ( author, commit_date, commit_date_instant, commit_id, commit_pk ) VALUES  ( ?,?,?,?,? )

	at org.javers.repository.sql.session.PreparedStatementExecutor.wrapExceptionAndCall(PreparedStatementExecutor.java:120)
	at org.javers.repository.sql.session.PreparedStatementExecutor.runVoidSql(PreparedStatementExecutor.java:110)
	at org.javers.repository.sql.session.PreparedStatementExecutor.execute(PreparedStatementExecutor.java:39)
	at org.javers.repository.sql.session.Session.execute(Session.java:104)
	at org.javers.repository.sql.session.Session.executeInsertAndGetSequence(Session.java:51)
	at org.javers.repository.sql.session.InsertBuilder.executeAndGetSequence(InsertBuilder.java:54)
	at org.javers.repository.sql.repositories.CommitMetadataRepository.save(CommitMetadataRepository.java:43)
	at org.javers.repository.sql.JaversSqlRepository.persist(JaversSqlRepository.java:89)
	at org.javers.repository.api.JaversExtendedRepository.persist(JaversExtendedRepository.java:154)
	at org.javers.core.JaversCore.persist(JaversCore.java:104)
	at org.javers.core.JaversCore.commit(JaversCore.java:85)
	at com.raise.base.repository.BaseRepository.auditEntity(BaseRepository.java:220)
	at com.raise.base.repository.BaseRepository.save(BaseRepository.java:107)
	at com.raise.base.repository.BaseRepositoryTest.testInsert(BaseRepositoryTest.java:139)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:532)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:171)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:167)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:114)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:59)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$4(NodeTestTask.java:108)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:98)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:74)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$4(NodeTestTask.java:112)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:98)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:74)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$4(NodeTestTask.java:112)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:98)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:74)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:220)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:188)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:202)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:181)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:74)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)`

**Comment by NicoBondarenco** [comment]
I ran all tests in javers-core with debug and it passes correctly, but when I ran "gradlew javers-core:test" there are some errors. I'm attaching the tests results, and I'll try to do some tests here too.


[nico-javers-test-result.zip](https://github.com/javers/javers/files/2730503/nico-javers-test-result.zip)

**Comment by NicoBondarenco** [comment]
My problem with the insert of "COMMIT_DATE_INSTANT" seems to be in "org.javers.repository.sql.repositories.CommitMetadataRepository.save()", in this specific serialization:
![image](https://user-images.githubusercontent.com/15568357/50737025-d90b7f80-11ab-11e9-8213-0f26e8cc7508.png)
`at org.javers.repository.sql.session.PreparedStatementExecutor.wrapExceptionAndCall(PreparedStatementExecutor.java:120)
	at org.javers.repository.sql.session.PreparedStatementExecutor.runVoidSql(PreparedStatementExecutor.java:110)
	at org.javers.repository.sql.session.PreparedStatementExecutor.execute(PreparedStatementExecutor.java:39)
	at org.javers.repository.sql.session.Session.execute(Session.java:104)
	at org.javers.repository.sql.session.Session.executeInsertAndGetSequence(Session.java:51)
	at org.javers.repository.sql.session.InsertBuilder.executeAndGetSequence(InsertBuilder.java:54)
	at org.javers.repository.sql.repositories.CommitMetadataRepository.save(CommitMetadataRepository.java:43)
	at org.javers.repository.sql.JaversSqlRepository.persist(JaversSqlRepository.java:89)
	at org.javers.repository.api.JaversExtendedRepository.persist(JaversExtendedRepository.java:154)
	at org.javers.core.JaversCore.persist(JaversCore.java:104)
	at org.javers.core.JaversCore.commit(JaversCore.java:85)`

**Comment by bartoszwalacik** [comment]
@NicoBondarenco, nice job, thanks. This is it. Fix is on its way to Central.

**Comment by bartoszwalacik** [comment]
fixed in 5.1.2

**Comment by bartoszwalacik** [comment]
second fix for this issue released in 5.1.3

**Comment by JacekWislicki** [comment]
5.1.2 works correctly, still I noticed exactly the same issue with 5.1.3.
