### ISSUE TITLE
CLASS_EXTRACTION_ERROR - Don't know how to extract Class from type 'T'

### ISSUE THREAD

**Issue by chosonnom** [javers/javers#773]
Hi this is regarding issue #77.
I am on Version 5.1.0 and I still see this issue.

My generics are not even complex.

```
public abstract class AbstractValueExample<T extends Serializable> implements Serializable {
    private Boolean option;
    private T value;
..................
}

public class BooleanValueExample extends AbstractValueExample<Boolean> {

}

public class SomeService {
     
      @Autowired
      private Javers javers;

     public void commitJavers(BooleanValueExample booleanValueExample) {
           Commit commit = javers.commit("author-me", booleanValueExample);
     }
}
```

This still produces the error below.  It can't figure out the T value on the

`private T value;`

===========================

Caused by: org.javers.common.exception.JaversException: CLASS_EXTRACTION_ERROR: JaVers bootstrap error - Can't extract Class from Type 'T'.
	at org.javers.common.reflection.ReflectionUtil.extractClass(ReflectionUtil.java:178) ~[javers-core-5.1.0.jar:?]
	at org.javers.core.metamodel.type.TypeMapperState.findPrototype(TypeMapperState.java:161) ~[javers-core-5.1.0.jar:?]
	at org.javers.core.metamodel.type.TypeMapperState.infer(TypeMapperState.java:157) ~[javers-core-5.1.0.jar:?]
	at org.javers.core.metamodel.type.TypeMapperState.lambda$getJaversType$0(TypeMapperState.java:89) ~[javers-core-5.1.0.jar:?]
	at org.javers.core.metamodel.type.TypeMapperState.computeIfAbsent(TypeMapperState.java:113) ~[javers-core-5.1.0.jar:?]
	at org.javers.core.metamodel.type.TypeMapperState.getJaversType(TypeMapperState.java:89) ~[javers-core-5.1.0.jar:?]
	at org.javers.core.metamodel.type.TypeMapper.getJaversType(TypeMapper.java:129) ~[javers-core-5.1.0.jar:?]
	at org.javers.core.metamodel.type.ManagedClassFactory.lambda$null$2(ManagedClassFactory.java:54) ~[javers-core-5.1.0.jar:?]
	at org.javers.core.metamodel.type.JaversProperty.getType(JaversProperty.java:23) ~[javers-core-5.1.0.jar:?]
	at org.javers.core.graph.ObjectGraphBuilder.lambda$getSingleReferencesWithManagedTypes$0(ObjectGraphBuilder.java:105) ~[javers-core-5.1.0.jar:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174) ~[?:1.8.0_181]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) ~[?:1.8.0_181]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_181]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_181]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_181]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_181]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_181]
	at org.javers.common.collections.Lists.positiveFilter(Lists.java:71) ~[javers-core-5.1.0.jar:?]
	at org.javers.core.metamodel.type.ManagedClass.getManagedProperties(ManagedClass.java:72) ~[javers-core-5.1.0.jar:?]
	at org.javers.core.metamodel.type.ManagedType.getProperties(ManagedType.java:55) ~[javers-core-5.1.0.jar:?]
	at org.javers.core.graph.ObjectGraphBuilder.getSingleReferencesWithManagedTypes(ObjectGraphBuilder.java:105) ~[javers-core-5.1.0.jar:?]
	at org.javers.core.graph.ObjectGraphBuilder.buildSingleEdges(ObjectGraphBuilder.java:75) ~[javers-core-5.1.0.jar:?]
	at org.javers.core.graph.ObjectGraphBuilder.buildEdges(ObjectGraphBuilder.java:70) ~[javers-core-5.1.0.jar:?]
	at org.javers.core.graph.ObjectGraphBuilder.buildGraphFromCdo(ObjectGraphBuilder.java:58) ~[javers-core-5.1.0.jar:?]
	at org.javers.core.graph.ObjectGraphBuilder.buildGraph(ObjectGraphBuilder.java:47) ~[javers-core-5.1.0.jar:?]
	at org.javers.core.graph.LiveGraphFactory.createLiveGraph(LiveGraphFactory.java:39) ~[javers-core-5.1.0.jar:?]
	at org.javers.core.commit.CommitFactory.createLiveGraph(CommitFactory.java:95) ~[javers-core-5.1.0.jar:?]
	at org.javers.core.commit.CommitFactory.create(CommitFactory.java:74) ~[javers-core-5.1.0.jar:?]
	at org.javers.core.JaversCore.commit(JaversCore.java:82) ~[javers-core-5.1.0.jar:?]
	at org.javers.core.JaversCore.commit(JaversCore.java:68) ~[javers-core-5.1.0.jar:?]
	at

**Comment by bartoszwalacik** [comment]
Hi, could you post a complete example, what objects are you comparing exactly?

**Comment by chosonnom** [comment]
I am not comparing, I just have a record and I am commiting it with Javer for audit log and I get this.

**Comment by mwesolowski** [comment]
@chosonnom I've tried to repeat the error in https://github.com/javers/javers/commit/59660f6b1ff5713da113c463a1784768064821a5. But my test finishes with success. Could you please provide a failing test?

**Comment by bartoszwalacik** [comment]
Ok, we will reopen this issue if you provide a failing test case.
