### ISSUE TITLE
java.lang.ClassCastException: class org.javers.core.metamodel.type.ValueObjectType cannot be cast to class org.javers.core.metamodel.type.PrimitiveOrValueType

### ISSUE THREAD

**Issue by pethers** [javers/javers#821]
Strange error, possible regression but not sure exactly when It started will test a few olders versions.

Version used : 5.3.4 (works with 5.2.6/5.3.2)

''java.lang.ClassCastException: class org.javers.core.metamodel.type.ValueObjectType cannot be cast to class org.javers.core.metamodel.type.PrimitiveOrValueType (org.javers.core.metamodel.type.ValueObjectType and org.javers.core.metamodel.type.PrimitiveOrValueType are in unnamed module of loader org.eclipse.jetty.webapp.WebAppClassLoader @1190200a)
	at org.javers.core.metamodel.type.EntityType.localIdAsString(EntityType.java:104)
	at org.javers.core.metamodel.type.EntityType.createIdFromInstance(EntityType.java:91)
	at org.javers.core.metamodel.object.GlobalIdFactory.createId(GlobalIdFactory.java:53)
	at org.javers.core.graph.LiveCdoFactory.create(LiveCdoFactory.java:38)
	at org.javers.core.graph.ObjectGraphBuilder.buildGraph(ObjectGraphBuilder.java:48)
	at org.javers.core.graph.LiveGraphFactory.createLiveGraph(LiveGraphFactory.java:38)
	at org.javers.core.commit.CommitFactory.createLiveGraph(CommitFactory.java:95)
	at org.javers.core.commit.CommitFactory.create(CommitFactory.java:74)
	at org.javers.core.JaversCore.commit(JaversCore.java:82)
	at org.javers.spring.jpa.JaversTransactionalDecorator.commit(JaversTransactionalDecorator.java:82)
	at org.javers.spring.auditable.aspect.JaversCommitAdvice.commitMethodArguments(JaversCommitAdvice.java:40)
	at org.javers.spring.auditable.aspect.JaversCommitAdvice.commitSaveMethodArguments(JaversCommitAdvice.java:28)
	at org.javers.spring.auditable.aspect.JaversAuditableAspect.commitAdvice(JaversAuditableAspect.java:37)''

**Comment by bartoszwalacik** [comment]
Test case with reproduction?

**Comment by pethers** [comment]
@bartoszwalacik will try to figure it out and provide it, only happens at one place in the application and works in other places.

**Comment by bartoszwalacik** [comment]
ok

**Comment by Sledzik** [comment]
I face with the same issue.
In my case I have an entity using composite primary key (@Embeddable) which cause the issue.
My workaround is to register the composite primary key class as Value
`.registerValue(JpaEntity.CompositeId.class)`

**Comment by bartoszwalacik** [comment]
try 5.3.5
