### ISSUE TITLE
ClassCastException: no type of entity change

### ISSUE THREAD

**Issue by vask00** [javers/javers#868]
I get this error. When I debug it has same value but different type. Old id Double,new BigDecimal.

Source entity field is BigDecimal and always was. No change on this field.

java.lang.ClassCastException: java.lang.Double cannot be cast to java.math.BigDecimal
     at org.javers.core.metamodel.type.PrimitiveOrValueType.equals(PrimitiveOrValueType.java:26)
     at org.javers.core.diff.appenders.ValueChangeAppender.calculateChanges(ValueChangeAppender.java:33)
     at org.javers.core.diff.appenders.ValueChangeAppender.calculateChanges(ValueChangeAppender.java:10)
     at org.javers.core.diff.DiffFactory.appendChanges(DiffFactory.java:153)
     at org.javers.core.diff.DiffFactory.appendPropertyChanges(DiffFactory.java:143)
     at org.javers.core.diff.DiffFactory.createAndAppendChanges(DiffFactory.java:125)
     at org.javers.core.diff.DiffFactory.create(DiffFactory.java:69)
     at org.javers.core.commit.CommitFactory.createCommit(CommitFactory.java:89)
     at org.javers.core.commit.CommitFactory.create(CommitFactory.java:75)
     at org.javers.core.JaversCore.commit(JaversCore.java:82)
     at name.berries.javers.JaversUtil.commit(JaversUtil.java:108)

**Comment by bartoszwalacik** [comment]
please push a failing test case (follow CONTRIBUTING.md)
