### ISSUE TITLE
Duplicate key name 'jv_global_id_owner_id_fk_idx' error when bootstrap with MYSQL Dialect

### ISSUE THREAD

**Issue by Rayer** [javers/javers#930]
Spring version : most recent
Javers artifact : javers-spring-boot-starter-sql 5.8.7

When trying to bootstrap, an exception is thrown :
```
2019-12-27 15:17:44.518 EFT [ID:] [PID:6064] [main] INFO  org.javers.repository.sql.schema.JaversSchemaManager - executing schema migration SQL:
CREATE INDEX jv_global_id_owner_id_fk_idx ON javers.jv_global_id(owner_id_fk)
2019-12-27 15:17:44.663 EFT [ID:] [PID:6064] [main] WARN  org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'JaversFromStarter' defined in class path resource [org/javers/spring/boot/sql/JaversSqlAutoConfiguration.class]: Invocation of init method failed; nested exception is java.lang.RuntimeException: java.sql.SQLSyntaxErrorException: Duplicate key name 'jv_global_id_owner_id_fk_idx'
2019-12-27 15:17:44.664 EFT [ID:] [PID:6064] [main] INFO  org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor - Shutting down ExecutorService 'applicationTaskExecutor'
2019-12-27 15:17:44.668 EFT [ID:] [PID:6064] [main] INFO  org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean - Closing JPA EntityManagerFactory for persistence unit 'default'
2019-12-27 15:17:44.670 EFT [ID:] [PID:6064] [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown initiated...
2019-12-27 15:17:44.680 EFT [ID:] [PID:6064] [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown completed.
2019-12-27 15:17:44.683 EFT [ID:] [PID:6064] [main] INFO  org.apache.catalina.core.StandardService - Stopping service [Tomcat]
2019-12-27 15:17:44.702 EFT [ID:] [PID:6064] [main] INFO  org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLoggingListener - 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2019-12-27 15:17:44.716 EFT [ID:] [PID:6064] [main] ERROR org.springframework.boot.SpringApplication - Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'JaversFromStarter' defined in class path resource [org/javers/spring/boot/sql/JaversSqlAutoConfiguration.class]: Invocation of init method failed; nested exception is java.lang.RuntimeException: java.sql.SQLSyntaxErrorException: Duplicate key name 'jv_global_id_owner_id_fk_idx'
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1803)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:595)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:879)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:878)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)
	at com.chc.enrollment.EftServiceApplication.main(EftServiceApplication.java:18)
Caused by: java.lang.RuntimeException: java.sql.SQLSyntaxErrorException: Duplicate key name 'jv_global_id_owner_id_fk_idx'
	at org.javers.repository.sql.schema.JaversSchemaManager.executeSQL(JaversSchemaManager.java:165)
	at org.javers.repository.sql.schema.JaversSchemaManager.addIndex(JaversSchemaManager.java:343)
	at org.javers.repository.sql.schema.JaversSchemaManager.addDbIndexOnOwnerId(JaversSchemaManager.java:102)
	at org.javers.repository.sql.schema.JaversSchemaManager.ensureSchema(JaversSchemaManager.java:61)
	at org.javers.repository.sql.JaversSqlRepository.ensureSchema(JaversSqlRepository.java:186)
	at org.javers.spring.jpa.JaversTransactionalDecorator$1.doInTransactionWithoutResult(JaversTransactionalDecorator.java:186)
	at org.springframework.transaction.support.TransactionCallbackWithoutResult.doInTransaction(TransactionCallbackWithoutResult.java:36)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140)
	at org.javers.spring.jpa.JaversTransactionalDecorator.ensureSchema(JaversTransactionalDecorator.java:183)
	at org.javers.spring.jpa.JaversTransactionalDecorator.afterPropertiesSet(JaversTransactionalDecorator.java:177)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1862)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1799)
	... 16 common frames omitted
Caused by: java.sql.SQLSyntaxErrorException: Duplicate key name 'jv_global_id_owner_id_fk_idx'
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.StatementImpl.executeInternal(StatementImpl.java:764)
	at com.mysql.cj.jdbc.StatementImpl.execute(StatementImpl.java:648)
	at com.zaxxer.hikari.pool.ProxyStatement.execute(ProxyStatement.java:95)
	at com.zaxxer.hikari.pool.HikariProxyStatement.execute(HikariProxyStatement.java)
	at org.javers.repository.sql.schema.JaversSchemaManager.executeSQL(JaversSchemaManager.java:160)
	... 27 common frames omitted

Process finished with exit code 1
```

After inspection, we have found issue comes from JaversSchemaManager.java line 60

```
        if(!(dialect instanceof H2Dialect)) {
            addDbIndexOnOwnerId();
        }

```

This function will create duplicated key which have been created before. All MYSQLDialect can reproduce this issue, and Oracle won't.

**Comment by bartoszwalacik** [comment]
Are you doing upgrade from Javers 3.11?

**Comment by Rayer** [comment]
No, totally fresh install on my new project

**Comment by bartoszwalacik** [comment]
Could you reproduce this issue in a failing test case? You can add it here https://github.com/javers/javers/blob/master/javers-persistence-sql/src/test/groovy/org/javers/repository/sql/integration/docker/MSSqlDockerIntegrationTest.groovy

We already have the test which proves that javers doesn't create its indexes and tables if they already exists:

```
   def "should not create jv_ tables if they already exists"(){
      given:
      def firstJavers = javers
      println "javers" + javers

      when:
      buildJaversInstance()
      println "javers" + javers

      then:
      firstJavers != javers
    }
```

**Comment by Rayer** [comment]
We can, but our crew hands are full recently, and it might require some time.

**Comment by bartoszwalacik** [comment]
Please reopen when you come up with a runnable test case
