### ISSUE TITLE
DocumentDB multiple fields of compound index cannot be arrays exception.

### ISSUE THREAD

**Issue by aravindaudupa** [javers/javers#957]
Hi there, I'm using Javers 5.8.13, on documentDB.
Javers.commit() is throwing exception as bellow. Is there any setting that I'm missing?
com.mongodb.MongoWriteException: multiple fields of compound index cannot be arrays
	at com.mongodb.client.internal.MongoCollectionImpl.executeSingleWriteRequest(MongoCollectionImpl.java:967)
	at com.mongodb.client.internal.MongoCollectionImpl.executeInsertOne(MongoCollectionImpl.java:494)
	at com.mongodb.client.internal.MongoCollectionImpl.insertOne(MongoCollectionImpl.java:478)
	at com.mongodb.client.internal.MongoCollectionImpl.insertOne(MongoCollectionImpl.java:472)
	at org.javers.repository.mongo.MongoRepository.lambda$persistSnapshots$3(MongoRepository.java:230)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1080)
	at org.javers.repository.mongo.MongoRepository.persistSnapshots(MongoRepository.java:229)
	at org.javers.repository.mongo.MongoRepository.persist(MongoRepository.java:87)
	at org.javers.repository.api.JaversExtendedRepository.persist(JaversExtendedRepository.java:154)
	at org.javers.core.JaversCore.persist(JaversCore.java:105)
	at org.javers.core.JaversCore.commit(JaversCore.java:86)
	at org.javers.core.JaversCore.commit(JaversCore.java:69)

**Comment by bartoszwalacik** [comment]
Hi, your config seems right, provide a failing test case.

**Comment by aravindaudupa** [comment]
@bartoszwalacik Also, is DocumentDB is still in Experimental support?

**Comment by bartoszwalacik** [comment]
Yes, as you can see :)

**Comment by bartoszwalacik** [comment]
I will reopen this issue if you provide a test case
